//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: D:\Java\git\core-ios-widgets\IOSSwipeRefreshLayoutPlugin\src\main\java\com\ashera\swiperefreshlayout\CustomSwipeRefreshLayoutImpl.java
//

#import <Foundation/Foundation.h>
#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_CustomSwipeRefreshLayoutImpl")
#ifdef RESTRICT_CustomSwipeRefreshLayoutImpl
#define INCLUDE_ALL_CustomSwipeRefreshLayoutImpl 0
#else
#define INCLUDE_ALL_CustomSwipeRefreshLayoutImpl 1
#endif
#undef RESTRICT_CustomSwipeRefreshLayoutImpl

#if !defined (ASCustomSwipeRefreshLayoutImpl_) && (INCLUDE_ALL_CustomSwipeRefreshLayoutImpl || defined(INCLUDE_ASCustomSwipeRefreshLayoutImpl))
#define ASCustomSwipeRefreshLayoutImpl_

#define RESTRICT_BaseHasWidgets 1
#define INCLUDE_ASBaseHasWidgets 1
#include "BaseHasWidgets.h"

@class ASWidgetAttribute;
@class IOSClass;
@class JavaLangBoolean;
@class JavaLangInteger;
@class NSString;
@protocol ASIFragment;
@protocol ASILifeCycleDecorator;
@protocol ASIWidget;
@protocol JavaUtilMap;

@interface ASCustomSwipeRefreshLayoutImpl : ASBaseHasWidgets
@property id uiView;

#pragma mark Public

- (instancetype)init;

- (instancetype)initWithNSString:(NSString *)localname;

- (instancetype)initWithNSString:(NSString *)groupName
                    withNSString:(NSString *)localname;

- (void)addWithASIWidget:(id<ASIWidget>)w
                 withInt:(int32_t)index;

- (id)asNativeWidget;

- (id)asWidget;

- (bool)checkIosVersionWithNSString:(NSString *)v;

- (void)createWithASIFragment:(id<ASIFragment>)fragment
              withJavaUtilMap:(id<JavaUtilMap>)params;

- (id)getAttributeWithASWidgetAttribute:(ASWidgetAttribute *)key
              withASILifeCycleDecorator:(id<ASILifeCycleDecorator>)decorator;

- (id)getChildAttributeWithASIWidget:(id<ASIWidget>)w
               withASWidgetAttribute:(ASWidgetAttribute *)key;

- (IOSClass *)getViewClass;

- (void)initialized OBJC_METHOD_FAMILY_NONE;

- (void)invalidate;

- (void)loadAttributesWithNSString:(NSString *)localName;

- (void)nativeCreateWithJavaUtilMap:(id<JavaUtilMap>)params;

- (id<ASIWidget>)newInstance OBJC_METHOD_FAMILY_NONE;

- (bool)removeWithInt:(int32_t)index;

- (bool)removeWithASIWidget:(id<ASIWidget>)w;

- (void)requestLayout;

- (void)setAttributeWithASWidgetAttribute:(ASWidgetAttribute *)key
                             withNSString:(NSString *)strValue
                                   withId:(id)objValue
                withASILifeCycleDecorator:(id<ASILifeCycleDecorator>)decorator;

- (void)setChildAttributeWithASIWidget:(id<ASIWidget>)w
                 withASWidgetAttribute:(ASWidgetAttribute *)key
                          withNSString:(NSString *)strValue
                                withId:(id)objValue;

- (void)setIdWithNSString:(NSString *)id_;

- (void)setVisibleWithBoolean:(bool)b;

@end

J2OBJC_EMPTY_STATIC_INIT(ASCustomSwipeRefreshLayoutImpl)

inline NSString *ASCustomSwipeRefreshLayoutImpl_get_LOCAL_NAME(void);
/*! INTERNAL ONLY - Use accessor function from above. */
FOUNDATION_EXPORT NSString *ASCustomSwipeRefreshLayoutImpl_LOCAL_NAME;
J2OBJC_STATIC_FIELD_OBJ_FINAL(ASCustomSwipeRefreshLayoutImpl, LOCAL_NAME, NSString *)

inline NSString *ASCustomSwipeRefreshLayoutImpl_get_GROUP_NAME(void);
/*! INTERNAL ONLY - Use accessor function from above. */
FOUNDATION_EXPORT NSString *ASCustomSwipeRefreshLayoutImpl_GROUP_NAME;
J2OBJC_STATIC_FIELD_OBJ_FINAL(ASCustomSwipeRefreshLayoutImpl, GROUP_NAME, NSString *)

FOUNDATION_EXPORT void ASCustomSwipeRefreshLayoutImpl_init(ASCustomSwipeRefreshLayoutImpl *self);

FOUNDATION_EXPORT ASCustomSwipeRefreshLayoutImpl *new_ASCustomSwipeRefreshLayoutImpl_init(void) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT ASCustomSwipeRefreshLayoutImpl *create_ASCustomSwipeRefreshLayoutImpl_init(void);

FOUNDATION_EXPORT void ASCustomSwipeRefreshLayoutImpl_initWithNSString_(ASCustomSwipeRefreshLayoutImpl *self, NSString *localname);

FOUNDATION_EXPORT ASCustomSwipeRefreshLayoutImpl *new_ASCustomSwipeRefreshLayoutImpl_initWithNSString_(NSString *localname) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT ASCustomSwipeRefreshLayoutImpl *create_ASCustomSwipeRefreshLayoutImpl_initWithNSString_(NSString *localname);

FOUNDATION_EXPORT void ASCustomSwipeRefreshLayoutImpl_initWithNSString_withNSString_(ASCustomSwipeRefreshLayoutImpl *self, NSString *groupName, NSString *localname);

FOUNDATION_EXPORT ASCustomSwipeRefreshLayoutImpl *new_ASCustomSwipeRefreshLayoutImpl_initWithNSString_withNSString_(NSString *groupName, NSString *localname) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT ASCustomSwipeRefreshLayoutImpl *create_ASCustomSwipeRefreshLayoutImpl_initWithNSString_withNSString_(NSString *groupName, NSString *localname);

J2OBJC_TYPE_LITERAL_HEADER(ASCustomSwipeRefreshLayoutImpl)

@compatibility_alias ComAsheraSwiperefreshlayoutCustomSwipeRefreshLayoutImpl ASCustomSwipeRefreshLayoutImpl;


#endif

#if !defined (ASCustomSwipeRefreshLayoutImpl_RefreshMode_) && (INCLUDE_ALL_CustomSwipeRefreshLayoutImpl || defined(INCLUDE_ASCustomSwipeRefreshLayoutImpl_RefreshMode))
#define ASCustomSwipeRefreshLayoutImpl_RefreshMode_

#define RESTRICT_AbstractEnumToIntConverter 1
#define INCLUDE_ASAbstractEnumToIntConverter 1
#include "AbstractEnumToIntConverter.h"

@class JavaLangInteger;
@protocol JavaUtilMap;

@interface ASCustomSwipeRefreshLayoutImpl_RefreshMode : ASAbstractEnumToIntConverter

#pragma mark Public

- (JavaLangInteger *)getDefault;

- (id<JavaUtilMap>)getMapping;

#pragma mark Package-Private

- (instancetype)init;

@end

J2OBJC_EMPTY_STATIC_INIT(ASCustomSwipeRefreshLayoutImpl_RefreshMode)

FOUNDATION_EXPORT void ASCustomSwipeRefreshLayoutImpl_RefreshMode_init(ASCustomSwipeRefreshLayoutImpl_RefreshMode *self);

FOUNDATION_EXPORT ASCustomSwipeRefreshLayoutImpl_RefreshMode *new_ASCustomSwipeRefreshLayoutImpl_RefreshMode_init(void) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT ASCustomSwipeRefreshLayoutImpl_RefreshMode *create_ASCustomSwipeRefreshLayoutImpl_RefreshMode_init(void);

J2OBJC_TYPE_LITERAL_HEADER(ASCustomSwipeRefreshLayoutImpl_RefreshMode)


#endif

#if !defined (ASCustomSwipeRefreshLayoutImpl_CustomSwipeRefreshLayoutExt_) && (INCLUDE_ALL_CustomSwipeRefreshLayoutImpl || defined(INCLUDE_ASCustomSwipeRefreshLayoutImpl_CustomSwipeRefreshLayoutExt))
#define ASCustomSwipeRefreshLayoutImpl_CustomSwipeRefreshLayoutExt_

#define RESTRICT_CustomSwipeRefreshLayout 1
#define INCLUDE_ASCustomSwipeRefreshLayout 1
#include "CustomSwipeRefreshLayout.h"

#define RESTRICT_ILifeCycleDecorator 1
#define INCLUDE_ASILifeCycleDecorator 1
#include "ILifeCycleDecorator.h"

#define RESTRICT_IMaxDimension 1
#define INCLUDE_ASIMaxDimension 1
#include "IMaxDimension.h"

@class ADRect;
@class ADView;
@class ASCustomSwipeRefreshLayoutImpl;
@class ASWidgetAttribute;
@class IOSIntArray;
@class IOSObjectArray;
@class JavaLangBoolean;
@class JavaLangInteger;
@class NSString;
@protocol ASIWidget;
@protocol JavaUtilList;

@interface ASCustomSwipeRefreshLayoutImpl_CustomSwipeRefreshLayoutExt : ASCustomSwipeRefreshLayout < ASILifeCycleDecorator, ASIMaxDimension >

#pragma mark Public

- (instancetype)initWithASCustomSwipeRefreshLayoutImpl:(ASCustomSwipeRefreshLayoutImpl *)outer$;

- (void)drawableStateChanged;

- (void)endViewTransitionWithADView:(ADView *)view;

- (void)executeWithNSString:(NSString *)method
          withNSObjectArray:(IOSObjectArray *)canvas;

- (id)getAttributeWithASWidgetAttribute:(ASWidgetAttribute *)widgetAttribute;

- (void)getLocationOnScreenWithIntArray:(IOSIntArray *)appScreenLocation;

- (int32_t)getMaxHeight;

- (int32_t)getMaxWidth;

- (id<JavaUtilList>)getMethods;

- (id<ASIWidget>)getWidget;

- (void)getWindowVisibleDisplayFrameWithADRect:(ADRect *)displayFrame;

- (ADView *)inflateViewWithNSString:(NSString *)layout;

- (void)initialized OBJC_METHOD_FAMILY_NONE;

- (id<ASILifeCycleDecorator>)newInstanceWithASIWidget:(id<ASIWidget>)widget OBJC_METHOD_FAMILY_NONE;

- (void)offsetLeftAndRightWithInt:(int32_t)offset;

- (void)offsetTopAndBottomWithInt:(int32_t)offset;

- (void)onMeasureWithInt:(int32_t)widthMeasureSpec
                 withInt:(int32_t)heightMeasureSpec;

- (void)remeasure;

- (void)removeFromParent;

- (void)setAttributeWithASWidgetAttribute:(ASWidgetAttribute *)widgetAttribute
                             withNSString:(NSString *)strValue
                                   withId:(id)objValue;

- (void)setMaxHeightWithInt:(int32_t)height;

- (void)setMaxWidthWithInt:(int32_t)width;

- (void)setMyAttributeWithNSString:(NSString *)name
                            withId:(id)value;

- (void)setState0WithId:(id)value;

- (void)setState1WithId:(id)value;

- (void)setState2WithId:(id)value;

- (void)setState3WithId:(id)value;

- (void)setState4WithId:(id)value;

- (void)setVisibilityWithInt:(int32_t)visibility;

- (void)state0;

- (void)state1;

- (void)state2;

- (void)state3;

- (void)state4;

- (void)stateNo;

- (void)stateYes;

- (void)updateMeasuredDimensionWithInt:(int32_t)width
                               withInt:(int32_t)height;

#pragma mark Protected

- (void)onLayoutWithBoolean:(bool)changed
                    withInt:(int32_t)l
                    withInt:(int32_t)t
                    withInt:(int32_t)r
                    withInt:(int32_t)b;

// Disallowed inherited constructors, do not use.

- (instancetype)init NS_UNAVAILABLE;

@end

J2OBJC_EMPTY_STATIC_INIT(ASCustomSwipeRefreshLayoutImpl_CustomSwipeRefreshLayoutExt)

FOUNDATION_EXPORT void ASCustomSwipeRefreshLayoutImpl_CustomSwipeRefreshLayoutExt_initWithASCustomSwipeRefreshLayoutImpl_(ASCustomSwipeRefreshLayoutImpl_CustomSwipeRefreshLayoutExt *self, ASCustomSwipeRefreshLayoutImpl *outer$);

FOUNDATION_EXPORT ASCustomSwipeRefreshLayoutImpl_CustomSwipeRefreshLayoutExt *new_ASCustomSwipeRefreshLayoutImpl_CustomSwipeRefreshLayoutExt_initWithASCustomSwipeRefreshLayoutImpl_(ASCustomSwipeRefreshLayoutImpl *outer$) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT ASCustomSwipeRefreshLayoutImpl_CustomSwipeRefreshLayoutExt *create_ASCustomSwipeRefreshLayoutImpl_CustomSwipeRefreshLayoutExt_initWithASCustomSwipeRefreshLayoutImpl_(ASCustomSwipeRefreshLayoutImpl *outer$);

J2OBJC_TYPE_LITERAL_HEADER(ASCustomSwipeRefreshLayoutImpl_CustomSwipeRefreshLayoutExt)


#endif

#pragma pop_macro("INCLUDE_ALL_CustomSwipeRefreshLayoutImpl")
