//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: D:\Java\git\core-ios-widgets\IOSSwipeRefreshLayoutPlugin\src\main\java\com\reginald\swiperefresh\CustomSwipeRefreshLayout.java
//

#import <Foundation/Foundation.h>
#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_CustomSwipeRefreshLayout")
#ifdef RESTRICT_CustomSwipeRefreshLayout
#define INCLUDE_ALL_CustomSwipeRefreshLayout 0
#else
#define INCLUDE_ALL_CustomSwipeRefreshLayout 1
#endif
#undef RESTRICT_CustomSwipeRefreshLayout

#if !defined (ASCustomSwipeRefreshLayout_) && (INCLUDE_ALL_CustomSwipeRefreshLayout || defined(INCLUDE_ASCustomSwipeRefreshLayout))
#define ASCustomSwipeRefreshLayout_

#define RESTRICT_ViewGroup 1
#define INCLUDE_ADViewGroup 1
#include "ViewGroup.h"

@class ADMotionEvent;
@class ADView;
@class ADViewGroup_LayoutParams;
@class ASCustomSwipeRefreshLayout_LayoutParams;
@class ASCustomSwipeRefreshLayout_State;
@class JavaLangBoolean;
@class JavaLangFloat;
@class JavaLangInteger;
@class NSString;
@protocol ASCustomSwipeRefreshLayout_OnRefreshListener;
@protocol ASCustomSwipeRefreshLayout_RefreshCheckHandler;
@protocol ASCustomSwipeRefreshLayout_ScrollLeftOrRightHandler;
@protocol ASCustomSwipeRefreshLayout_ScrollUpHandler;

@interface ASCustomSwipeRefreshLayout : ADViewGroup {
 @public
  bool enableTopProgressBar_;
  bool keepTopRefreshingHead_;
  int32_t refresshMode_;
  ASCustomSwipeRefreshLayout_State *currentState_;
  ASCustomSwipeRefreshLayout_State *lastState_;
}

#pragma mark Public

- (instancetype)init;

- (void)addViewWithADView:(ADView *)child
                  withInt:(int32_t)index
withASCustomSwipeRefreshLayout_LayoutParams:(ASCustomSwipeRefreshLayout_LayoutParams *)params;

- (void)enableTopProgressBarWithBoolean:(bool)isEnable;

- (int32_t)getProgressBarHeight;

- (int32_t)getRefreshCompleteTimeout;

- (int32_t)getRefreshMode;

- (float)getResistanceFactor;

- (int32_t)getReturnToHeaderDuration;

- (int32_t)getReturnToOriginalTimeout;

- (int32_t)getReturnToTopDuration;

- (int32_t)getTriggerDistance;

- (bool)isKeepTopRefreshingHead;

- (bool)isRefreshing;

- (void)onAttachedToWindow;

- (void)onDetachedFromWindow;

- (bool)onInterceptTouchEventWithADMotionEvent:(ADMotionEvent *)ev;

- (bool)onTouchEventWithADMotionEvent:(ADMotionEvent *)event;

- (void)refreshComplete;

- (void)requestDisallowInterceptTouchEventWithBoolean:(bool)b;

- (void)setCustomHeaderLayoutWithNSString:(NSString *)layout;

- (void)setCustomHeadviewWithADView:(ADView *)customHeadview;

- (void)setEnableHorizontalScrollWithBoolean:(bool)isEnable;

- (void)setKeepTopRefreshingHeadWithBoolean:(bool)isEnable;

- (void)setOnRefreshListenerWithASCustomSwipeRefreshLayout_OnRefreshListener:(id<ASCustomSwipeRefreshLayout_OnRefreshListener>)listener;

- (void)setProgressBarColorWithId:(id)color1
                           withId:(id)color2
                           withId:(id)color3
                           withId:(id)color4;

- (void)setProgressBarHeightWithInt:(int32_t)height;

- (void)setRefreshCheckHandlerWithASCustomSwipeRefreshLayout_RefreshCheckHandler:(id<ASCustomSwipeRefreshLayout_RefreshCheckHandler>)handler;

- (void)setRefreshCompleteTimeoutWithInt:(int32_t)mRefreshCompleteTimeout;

- (void)setRefreshModeWithInt:(int32_t)mode;

- (void)setResistanceFactorWithFloat:(float)factor;

- (void)setReturnToHeaderDurationWithInt:(int32_t)duration;

- (void)setReturnToOriginalTimeoutWithInt:(int32_t)mReturnToOriginalTimeout;

- (void)setReturnToTopDurationWithInt:(int32_t)duration;

- (void)setScroolLeftOrRightHandlerWithASCustomSwipeRefreshLayout_ScrollLeftOrRightHandler:(id<ASCustomSwipeRefreshLayout_ScrollLeftOrRightHandler>)handler;

- (void)setScroolUpHandlerWithASCustomSwipeRefreshLayout_ScrollUpHandler:(id<ASCustomSwipeRefreshLayout_ScrollUpHandler>)handler;

- (void)setTriggerDistanceWithInt:(int32_t)distance;

- (void)setWebHeaderZIndexWithId:(id)objValue;

#pragma mark Protected

- (bool)checkLayoutParamsWithADViewGroup_LayoutParams:(ADViewGroup_LayoutParams *)p;

- (ADViewGroup_LayoutParams *)generateDefaultLayoutParams;

- (void)onLayoutWithBoolean:(bool)changed
                    withInt:(int32_t)left
                    withInt:(int32_t)top
                    withInt:(int32_t)right
                    withInt:(int32_t)bottom;

- (void)onMeasureWithInt:(int32_t)widthMeasureSpec
                 withInt:(int32_t)heightMeasureSpec;

- (void)setRefreshingWithBoolean:(bool)refreshing;

@end

J2OBJC_EMPTY_STATIC_INIT(ASCustomSwipeRefreshLayout)

J2OBJC_FIELD_SETTER(ASCustomSwipeRefreshLayout, currentState_, ASCustomSwipeRefreshLayout_State *)
J2OBJC_FIELD_SETTER(ASCustomSwipeRefreshLayout, lastState_, ASCustomSwipeRefreshLayout_State *)

inline bool ASCustomSwipeRefreshLayout_get_DEBUG(void);
#define ASCustomSwipeRefreshLayout_DEBUG false
J2OBJC_STATIC_FIELD_CONSTANT(ASCustomSwipeRefreshLayout, DEBUG, bool)

inline NSString *ASCustomSwipeRefreshLayout_get_TAG(void);
/*! INTERNAL ONLY - Use accessor function from above. */
FOUNDATION_EXPORT NSString *ASCustomSwipeRefreshLayout_TAG;
J2OBJC_STATIC_FIELD_OBJ_FINAL(ASCustomSwipeRefreshLayout, TAG, NSString *)

inline int32_t ASCustomSwipeRefreshLayout_get_REFRESH_MODE_SWIPE(void);
#define ASCustomSwipeRefreshLayout_REFRESH_MODE_SWIPE 1
J2OBJC_STATIC_FIELD_CONSTANT(ASCustomSwipeRefreshLayout, REFRESH_MODE_SWIPE, int32_t)

inline int32_t ASCustomSwipeRefreshLayout_get_REFRESH_MODE_PULL(void);
#define ASCustomSwipeRefreshLayout_REFRESH_MODE_PULL 2
J2OBJC_STATIC_FIELD_CONSTANT(ASCustomSwipeRefreshLayout, REFRESH_MODE_PULL, int32_t)

FOUNDATION_EXPORT void ASCustomSwipeRefreshLayout_init(ASCustomSwipeRefreshLayout *self);

FOUNDATION_EXPORT ASCustomSwipeRefreshLayout *new_ASCustomSwipeRefreshLayout_init(void) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT ASCustomSwipeRefreshLayout *create_ASCustomSwipeRefreshLayout_init(void);

J2OBJC_TYPE_LITERAL_HEADER(ASCustomSwipeRefreshLayout)

@compatibility_alias ComReginaldSwiperefreshCustomSwipeRefreshLayout ASCustomSwipeRefreshLayout;


#endif

#if !defined (ASCustomSwipeRefreshLayout_OnRefreshListener_) && (INCLUDE_ALL_CustomSwipeRefreshLayout || defined(INCLUDE_ASCustomSwipeRefreshLayout_OnRefreshListener))
#define ASCustomSwipeRefreshLayout_OnRefreshListener_

@protocol ASCustomSwipeRefreshLayout_OnRefreshListener < JavaObject >

- (void)onRefresh;

@end

J2OBJC_EMPTY_STATIC_INIT(ASCustomSwipeRefreshLayout_OnRefreshListener)

J2OBJC_TYPE_LITERAL_HEADER(ASCustomSwipeRefreshLayout_OnRefreshListener)


#endif

#if !defined (ASCustomSwipeRefreshLayout_RefreshCheckHandler_) && (INCLUDE_ALL_CustomSwipeRefreshLayout || defined(INCLUDE_ASCustomSwipeRefreshLayout_RefreshCheckHandler))
#define ASCustomSwipeRefreshLayout_RefreshCheckHandler_

@class JavaLangBoolean;

@protocol ASCustomSwipeRefreshLayout_RefreshCheckHandler < JavaObject >

- (bool)canRefresh;

@end

J2OBJC_EMPTY_STATIC_INIT(ASCustomSwipeRefreshLayout_RefreshCheckHandler)

J2OBJC_TYPE_LITERAL_HEADER(ASCustomSwipeRefreshLayout_RefreshCheckHandler)


#endif

#if !defined (ASCustomSwipeRefreshLayout_ScrollUpHandler_) && (INCLUDE_ALL_CustomSwipeRefreshLayout || defined(INCLUDE_ASCustomSwipeRefreshLayout_ScrollUpHandler))
#define ASCustomSwipeRefreshLayout_ScrollUpHandler_

@class ADView;
@class JavaLangBoolean;

@protocol ASCustomSwipeRefreshLayout_ScrollUpHandler < JavaObject >

- (bool)canScrollUpWithADView:(ADView *)view;

@end

J2OBJC_EMPTY_STATIC_INIT(ASCustomSwipeRefreshLayout_ScrollUpHandler)

J2OBJC_TYPE_LITERAL_HEADER(ASCustomSwipeRefreshLayout_ScrollUpHandler)


#endif

#if !defined (ASCustomSwipeRefreshLayout_ScrollLeftOrRightHandler_) && (INCLUDE_ALL_CustomSwipeRefreshLayout || defined(INCLUDE_ASCustomSwipeRefreshLayout_ScrollLeftOrRightHandler))
#define ASCustomSwipeRefreshLayout_ScrollLeftOrRightHandler_

@class ADView;
@class JavaLangBoolean;
@class JavaLangInteger;

@protocol ASCustomSwipeRefreshLayout_ScrollLeftOrRightHandler < JavaObject >

- (bool)canScrollLeftOrRightWithADView:(ADView *)view
                               withInt:(int32_t)direction;

@end

J2OBJC_EMPTY_STATIC_INIT(ASCustomSwipeRefreshLayout_ScrollLeftOrRightHandler)

J2OBJC_TYPE_LITERAL_HEADER(ASCustomSwipeRefreshLayout_ScrollLeftOrRightHandler)


#endif

#if !defined (ASCustomSwipeRefreshLayout_CustomSwipeRefreshHeadLayout_) && (INCLUDE_ALL_CustomSwipeRefreshLayout || defined(INCLUDE_ASCustomSwipeRefreshLayout_CustomSwipeRefreshHeadLayout))
#define ASCustomSwipeRefreshLayout_CustomSwipeRefreshHeadLayout_

@class ASCustomSwipeRefreshLayout_State;

@protocol ASCustomSwipeRefreshLayout_CustomSwipeRefreshHeadLayout < JavaObject >

- (void)onStateChangeWithASCustomSwipeRefreshLayout_State:(ASCustomSwipeRefreshLayout_State *)currentState
                     withASCustomSwipeRefreshLayout_State:(ASCustomSwipeRefreshLayout_State *)lastState;

@end

J2OBJC_EMPTY_STATIC_INIT(ASCustomSwipeRefreshLayout_CustomSwipeRefreshHeadLayout)

J2OBJC_TYPE_LITERAL_HEADER(ASCustomSwipeRefreshLayout_CustomSwipeRefreshHeadLayout)


#endif

#if !defined (ASCustomSwipeRefreshLayout_State_) && (INCLUDE_ALL_CustomSwipeRefreshLayout || defined(INCLUDE_ASCustomSwipeRefreshLayout_State))
#define ASCustomSwipeRefreshLayout_State_

@class JavaLangFloat;
@class JavaLangInteger;
@class NSString;

@interface ASCustomSwipeRefreshLayout_State : NSObject

#pragma mark Public

- (instancetype)initWithInt:(int32_t)refreshState;

- (int32_t)getHeaderTop;

- (float)getPercent;

- (int32_t)getRefreshState;

- (int32_t)getTrigger;

- (NSString *)description;

#pragma mark Package-Private

- (void)updateWithInt:(int32_t)refreshState
              withInt:(int32_t)top
              withInt:(int32_t)trigger;

// Disallowed inherited constructors, do not use.

- (instancetype)init NS_UNAVAILABLE;

@end

J2OBJC_EMPTY_STATIC_INIT(ASCustomSwipeRefreshLayout_State)

inline int32_t ASCustomSwipeRefreshLayout_State_get_STATE_NORMAL(void);
#define ASCustomSwipeRefreshLayout_State_STATE_NORMAL 0
J2OBJC_STATIC_FIELD_CONSTANT(ASCustomSwipeRefreshLayout_State, STATE_NORMAL, int32_t)

inline int32_t ASCustomSwipeRefreshLayout_State_get_STATE_READY(void);
#define ASCustomSwipeRefreshLayout_State_STATE_READY 1
J2OBJC_STATIC_FIELD_CONSTANT(ASCustomSwipeRefreshLayout_State, STATE_READY, int32_t)

inline int32_t ASCustomSwipeRefreshLayout_State_get_STATE_REFRESHING(void);
#define ASCustomSwipeRefreshLayout_State_STATE_REFRESHING 2
J2OBJC_STATIC_FIELD_CONSTANT(ASCustomSwipeRefreshLayout_State, STATE_REFRESHING, int32_t)

inline int32_t ASCustomSwipeRefreshLayout_State_get_STATE_COMPLETE(void);
#define ASCustomSwipeRefreshLayout_State_STATE_COMPLETE 3
J2OBJC_STATIC_FIELD_CONSTANT(ASCustomSwipeRefreshLayout_State, STATE_COMPLETE, int32_t)

FOUNDATION_EXPORT void ASCustomSwipeRefreshLayout_State_initWithInt_(ASCustomSwipeRefreshLayout_State *self, int32_t refreshState);

FOUNDATION_EXPORT ASCustomSwipeRefreshLayout_State *new_ASCustomSwipeRefreshLayout_State_initWithInt_(int32_t refreshState) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT ASCustomSwipeRefreshLayout_State *create_ASCustomSwipeRefreshLayout_State_initWithInt_(int32_t refreshState);

J2OBJC_TYPE_LITERAL_HEADER(ASCustomSwipeRefreshLayout_State)


#endif

#if !defined (ASCustomSwipeRefreshLayout_LayoutParams_) && (INCLUDE_ALL_CustomSwipeRefreshLayout || defined(INCLUDE_ASCustomSwipeRefreshLayout_LayoutParams))
#define ASCustomSwipeRefreshLayout_LayoutParams_

#define RESTRICT_ViewGroup 1
#define INCLUDE_ADViewGroup_MarginLayoutParams 1
#include "ViewGroup.h"

@class ADViewGroup_LayoutParams;
@class JavaLangInteger;

@interface ASCustomSwipeRefreshLayout_LayoutParams : ADViewGroup_MarginLayoutParams

#pragma mark Public

- (instancetype)initWithInt:(int32_t)width
                    withInt:(int32_t)height;

// Disallowed inherited constructors, do not use.

- (instancetype)initWithADViewGroup_LayoutParams:(ADViewGroup_LayoutParams *)arg0 NS_UNAVAILABLE;

- (instancetype)initWithADViewGroup_MarginLayoutParams:(ADViewGroup_MarginLayoutParams *)arg0 NS_UNAVAILABLE;

@end

J2OBJC_EMPTY_STATIC_INIT(ASCustomSwipeRefreshLayout_LayoutParams)

FOUNDATION_EXPORT void ASCustomSwipeRefreshLayout_LayoutParams_initWithInt_withInt_(ASCustomSwipeRefreshLayout_LayoutParams *self, int32_t width, int32_t height);

FOUNDATION_EXPORT ASCustomSwipeRefreshLayout_LayoutParams *new_ASCustomSwipeRefreshLayout_LayoutParams_initWithInt_withInt_(int32_t width, int32_t height) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT ASCustomSwipeRefreshLayout_LayoutParams *create_ASCustomSwipeRefreshLayout_LayoutParams_initWithInt_withInt_(int32_t width, int32_t height);

J2OBJC_TYPE_LITERAL_HEADER(ASCustomSwipeRefreshLayout_LayoutParams)


#endif

#pragma pop_macro("INCLUDE_ALL_CustomSwipeRefreshLayout")
