//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: D:\Java\git\core-ios-widgets\IOSSwipeRefreshLayoutPlugin\src\main\java\com\reginald\swiperefresh\CustomSwipeProgressBar.java
//

#import <Foundation/Foundation.h>
#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_CustomSwipeProgressBar")
#ifdef RESTRICT_CustomSwipeProgressBar
#define INCLUDE_ALL_CustomSwipeProgressBar 0
#else
#define INCLUDE_ALL_CustomSwipeProgressBar 1
#endif
#undef RESTRICT_CustomSwipeProgressBar

#if !defined (ASCustomSwipeProgressBar_) && (INCLUDE_ALL_CustomSwipeProgressBar || defined(INCLUDE_ASCustomSwipeProgressBar))
#define ASCustomSwipeProgressBar_

@class ADView;
@class JavaLangFloat;
@class JavaLangInteger;

@interface ASCustomSwipeProgressBar : NSObject
@property id lineSwipeProgressBar;

#pragma mark Public

- (instancetype)initWithADView:(ADView *)parent;

- (void)nativeCreate;

- (void)nativesetProgressBarColorWithId:(id)c1
                                 withId:(id)c2
                                 withId:(id)c3
                                 withId:(id)c4
                                 withId:(id)view;

- (void)nativeSetTriggerPercentageWithFloat:(float)f
                                     withId:(id)view;

- (void)nativeStartWithId:(id)view;

- (void)nativeStopWithId:(id)view;

- (void)setBoundsWithInt:(int32_t)left
                 withInt:(int32_t)top
                 withInt:(int32_t)right
                 withInt:(int32_t)bottom;

- (void)setProgressBarColorWithId:(id)color1
                           withId:(id)color2
                           withId:(id)color3
                           withId:(id)color4;

- (void)setTriggerPercentageWithFloat:(float)f;

- (void)start;

- (void)stop;

// Disallowed inherited constructors, do not use.

- (instancetype)init NS_UNAVAILABLE;

@end

J2OBJC_EMPTY_STATIC_INIT(ASCustomSwipeProgressBar)

FOUNDATION_EXPORT void ASCustomSwipeProgressBar_initWithADView_(ASCustomSwipeProgressBar *self, ADView *parent);

FOUNDATION_EXPORT ASCustomSwipeProgressBar *new_ASCustomSwipeProgressBar_initWithADView_(ADView *parent) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT ASCustomSwipeProgressBar *create_ASCustomSwipeProgressBar_initWithADView_(ADView *parent);

J2OBJC_TYPE_LITERAL_HEADER(ASCustomSwipeProgressBar)

@compatibility_alias ComReginaldSwiperefreshCustomSwipeProgressBar ASCustomSwipeProgressBar;


#endif

#pragma pop_macro("INCLUDE_ALL_CustomSwipeProgressBar")
