//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: D:\Java\git\core-ios-widgets\IOSSwipeRefreshLayoutPlugin\src\main\java\com\ashera\swiperefreshlayout\CustomSwipeRefreshLayoutImpl.java
//

#define J2OBJC_IMPORTED_BY_JAVA_IMPLEMENTATION 1




#include "AbstractEnumToIntConverter.h"
#include "BaseHasWidgets.h"
#include "ConverterFactory.h"
#include "CustomSwipeRefreshLayout.h"
#include "CustomSwipeRefreshLayoutImpl.h"
#include "EventBus.h"
#include "EventCommand.h"
#include "EventCommandFactory.h"
#include "EventExpressionParser.h"
#include "HasWidgets.h"
#include "IActivity.h"
#include "IFragment.h"
#include "ILifeCycleDecorator.h"
#include "IListener.h"
#include "IOSClass.h"
#include "IOSObjectArray.h"
#include "IOSPrimitiveArray.h"
#include "IWidget.h"
#include "IWidgetLifeCycleListener.h"
#include "J2ObjC_source.h"
#include "LayoutTransition.h"
#include "MeasureEvent.h"
#include "MotionEvent.h"
#include "OnLayoutEvent.h"
#include "PluginInvoker.h"
#include "Rect.h"
#include "View.h"
#include "ViewGroup.h"
#include "ViewGroupImpl.h"
#include "ViewImpl.h"
#include "WidgetAttribute.h"
#include "WidgetFactory.h"
#include "java/lang/Boolean.h"
#include "java/lang/Float.h"
#include "java/lang/Integer.h"
#include "java/lang/Runnable.h"
#include "java/lang/RuntimeException.h"
#include "java/lang/UnsupportedOperationException.h"
#include "java/util/HashMap.h"
#include "java/util/List.h"
#include "java/util/Map.h"

#include <UIKit/UIKit.h>
#include "ASUIView.h"
#include "HasLifeCycleDecorators.h"


@class NSString;


#pragma clang diagnostic error "-Wreturn-type"
#pragma clang diagnostic ignored "-Wswitch"


#pragma clang diagnostic ignored "-Wprotocol"

@interface ASCustomSwipeRefreshLayoutImpl () {
 @public
  id uiView_;
  ASCustomSwipeRefreshLayout *customSwipeRefreshLayout_;
  int32_t action_;
  ADMotionEvent *event_;
}

- (void)setWidgetOnNativeClass;

- (void)nativeRemoveViewWithASIWidget:(id<ASIWidget>)widget;

- (void)createLayoutParamsWithADView:(ADView *)view;

- (ASCustomSwipeRefreshLayout_LayoutParams *)getLayoutParamsWithADView:(ADView *)view;

- (void)setCustomHeadLayoutWithId:(id)objValue;

- (void)setTopProgressBarColorSchemeWithId:(id)objValue;

- (bool)processTouchEventWithInt:(int32_t)action
                         withInt:(int32_t)x
                         withInt:(int32_t)y;

@end

J2OBJC_FIELD_SETTER(ASCustomSwipeRefreshLayoutImpl, uiView_, id)
J2OBJC_FIELD_SETTER(ASCustomSwipeRefreshLayoutImpl, customSwipeRefreshLayout_, ASCustomSwipeRefreshLayout *)
J2OBJC_FIELD_SETTER(ASCustomSwipeRefreshLayoutImpl, event_, ADMotionEvent *)

__attribute__((unused)) static void ASCustomSwipeRefreshLayoutImpl_setWidgetOnNativeClass(ASCustomSwipeRefreshLayoutImpl *self);

__attribute__((unused)) static void ASCustomSwipeRefreshLayoutImpl_nativeRemoveViewWithASIWidget_(ASCustomSwipeRefreshLayoutImpl *self, id<ASIWidget> widget);

__attribute__((unused)) static void ASCustomSwipeRefreshLayoutImpl_createLayoutParamsWithADView_(ASCustomSwipeRefreshLayoutImpl *self, ADView *view);

__attribute__((unused)) static ASCustomSwipeRefreshLayout_LayoutParams *ASCustomSwipeRefreshLayoutImpl_getLayoutParamsWithADView_(ASCustomSwipeRefreshLayoutImpl *self, ADView *view);

__attribute__((unused)) static void ASCustomSwipeRefreshLayoutImpl_setCustomHeadLayoutWithId_(ASCustomSwipeRefreshLayoutImpl *self, id objValue);

__attribute__((unused)) static void ASCustomSwipeRefreshLayoutImpl_setTopProgressBarColorSchemeWithId_(ASCustomSwipeRefreshLayoutImpl *self, id objValue);

__attribute__((unused)) static bool ASCustomSwipeRefreshLayoutImpl_processTouchEventWithInt_withInt_withInt_(ASCustomSwipeRefreshLayoutImpl *self, int32_t action, int32_t x, int32_t y);

@interface ASCustomSwipeRefreshLayoutImpl_RefreshMode () {
 @public
  id<JavaUtilMap> mapping_;
}

@end

J2OBJC_FIELD_SETTER(ASCustomSwipeRefreshLayoutImpl_RefreshMode, mapping_, id<JavaUtilMap>)

@interface ASCustomSwipeRefreshLayoutImpl_CustomSwipeRefreshLayoutExt () {
 @public
  WEAK_ ASCustomSwipeRefreshLayoutImpl *this$0_;
  ASMeasureEvent *measureFinished_;
  ASOnLayoutEvent *onLayoutEvent_;
  id<JavaUtilList> overlays_;
  int32_t mMaxWidth_;
  int32_t mMaxHeight_;
  id<JavaUtilMap> templates_;
}

@end

J2OBJC_FIELD_SETTER(ASCustomSwipeRefreshLayoutImpl_CustomSwipeRefreshLayoutExt, measureFinished_, ASMeasureEvent *)
J2OBJC_FIELD_SETTER(ASCustomSwipeRefreshLayoutImpl_CustomSwipeRefreshLayoutExt, onLayoutEvent_, ASOnLayoutEvent *)
J2OBJC_FIELD_SETTER(ASCustomSwipeRefreshLayoutImpl_CustomSwipeRefreshLayoutExt, overlays_, id<JavaUtilList>)
J2OBJC_FIELD_SETTER(ASCustomSwipeRefreshLayoutImpl_CustomSwipeRefreshLayoutExt, templates_, id<JavaUtilMap>)

@interface ASCustomSwipeRefreshLayoutImpl_OnRefreshListener : NSObject < ASCustomSwipeRefreshLayout_OnRefreshListener, ASIListener > {
 @public
  id<ASIWidget> w_;
  ADView *view_;
  NSString *strValue_;
  NSString *action_;
}

- (NSString *)getAction;

- (instancetype)initWithASIWidget:(id<ASIWidget>)w
                     withNSString:(NSString *)strValue;

- (instancetype)initWithASIWidget:(id<ASIWidget>)w
                     withNSString:(NSString *)strValue
                     withNSString:(NSString *)action;

- (void)onRefresh;

- (id<JavaUtilMap>)getOnRefreshEventObj;

@end

J2OBJC_EMPTY_STATIC_INIT(ASCustomSwipeRefreshLayoutImpl_OnRefreshListener)

J2OBJC_FIELD_SETTER(ASCustomSwipeRefreshLayoutImpl_OnRefreshListener, w_, id<ASIWidget>)
J2OBJC_FIELD_SETTER(ASCustomSwipeRefreshLayoutImpl_OnRefreshListener, view_, ADView *)
J2OBJC_FIELD_SETTER(ASCustomSwipeRefreshLayoutImpl_OnRefreshListener, strValue_, NSString *)
J2OBJC_FIELD_SETTER(ASCustomSwipeRefreshLayoutImpl_OnRefreshListener, action_, NSString *)

__attribute__((unused)) static void ASCustomSwipeRefreshLayoutImpl_OnRefreshListener_initWithASIWidget_withNSString_(ASCustomSwipeRefreshLayoutImpl_OnRefreshListener *self, id<ASIWidget> w, NSString *strValue);

__attribute__((unused)) static ASCustomSwipeRefreshLayoutImpl_OnRefreshListener *new_ASCustomSwipeRefreshLayoutImpl_OnRefreshListener_initWithASIWidget_withNSString_(id<ASIWidget> w, NSString *strValue) NS_RETURNS_RETAINED;

__attribute__((unused)) static ASCustomSwipeRefreshLayoutImpl_OnRefreshListener *create_ASCustomSwipeRefreshLayoutImpl_OnRefreshListener_initWithASIWidget_withNSString_(id<ASIWidget> w, NSString *strValue);

__attribute__((unused)) static void ASCustomSwipeRefreshLayoutImpl_OnRefreshListener_initWithASIWidget_withNSString_withNSString_(ASCustomSwipeRefreshLayoutImpl_OnRefreshListener *self, id<ASIWidget> w, NSString *strValue, NSString *action);

__attribute__((unused)) static ASCustomSwipeRefreshLayoutImpl_OnRefreshListener *new_ASCustomSwipeRefreshLayoutImpl_OnRefreshListener_initWithASIWidget_withNSString_withNSString_(id<ASIWidget> w, NSString *strValue, NSString *action) NS_RETURNS_RETAINED;

__attribute__((unused)) static ASCustomSwipeRefreshLayoutImpl_OnRefreshListener *create_ASCustomSwipeRefreshLayoutImpl_OnRefreshListener_initWithASIWidget_withNSString_withNSString_(id<ASIWidget> w, NSString *strValue, NSString *action);

J2OBJC_TYPE_LITERAL_HEADER(ASCustomSwipeRefreshLayoutImpl_OnRefreshListener)


@interface ASCustomSwipeRefreshLayoutImpl_1 : NSObject < ASViewImpl_PanCallBack > {
 @public
  ASCustomSwipeRefreshLayoutImpl *this$0_;
}

- (instancetype)initWithASCustomSwipeRefreshLayoutImpl:(ASCustomSwipeRefreshLayoutImpl *)outer$;

- (void)handlePanStartWithASIWidget:(id<ASIWidget>)widget
                             withId:(id)eventWidget
                            withInt:(int32_t)x
                            withInt:(int32_t)y;

- (void)handlePanDragWithASIWidget:(id<ASIWidget>)widget
                            withId:(id)eventWidget
                           withInt:(int32_t)x
                           withInt:(int32_t)y;

- (void)handlePanEndWithASIWidget:(id<ASIWidget>)widget
                           withId:(id)eventWidget
                          withInt:(int32_t)x
                          withInt:(int32_t)y;

@end

J2OBJC_EMPTY_STATIC_INIT(ASCustomSwipeRefreshLayoutImpl_1)

__attribute__((unused)) static void ASCustomSwipeRefreshLayoutImpl_1_initWithASCustomSwipeRefreshLayoutImpl_(ASCustomSwipeRefreshLayoutImpl_1 *self, ASCustomSwipeRefreshLayoutImpl *outer$);

__attribute__((unused)) static ASCustomSwipeRefreshLayoutImpl_1 *new_ASCustomSwipeRefreshLayoutImpl_1_initWithASCustomSwipeRefreshLayoutImpl_(ASCustomSwipeRefreshLayoutImpl *outer$) NS_RETURNS_RETAINED;

__attribute__((unused)) static ASCustomSwipeRefreshLayoutImpl_1 *create_ASCustomSwipeRefreshLayoutImpl_1_initWithASCustomSwipeRefreshLayoutImpl_(ASCustomSwipeRefreshLayoutImpl *outer$);


@interface ASCustomSwipeRefreshLayoutImpl_$Lambda$1 : NSObject < JavaLangRunnable > {
 @public
  id<ASIWidget> val$widget_;
}

- (void)run;

@end

J2OBJC_EMPTY_STATIC_INIT(ASCustomSwipeRefreshLayoutImpl_$Lambda$1)

__attribute__((unused)) static void ASCustomSwipeRefreshLayoutImpl_$Lambda$1_initWithASIWidget_(ASCustomSwipeRefreshLayoutImpl_$Lambda$1 *self, id<ASIWidget> capture$0);

__attribute__((unused)) static ASCustomSwipeRefreshLayoutImpl_$Lambda$1 *new_ASCustomSwipeRefreshLayoutImpl_$Lambda$1_initWithASIWidget_(id<ASIWidget> capture$0) NS_RETURNS_RETAINED;

__attribute__((unused)) static ASCustomSwipeRefreshLayoutImpl_$Lambda$1 *create_ASCustomSwipeRefreshLayoutImpl_$Lambda$1_initWithASIWidget_(id<ASIWidget> capture$0);


NSString *ASCustomSwipeRefreshLayoutImpl_LOCAL_NAME = @"com.reginald.swiperefresh.CustomSwipeRefreshLayout";
NSString *ASCustomSwipeRefreshLayoutImpl_GROUP_NAME = @"com.reginald.swiperefresh.CustomSwipeRefreshLayout";

@implementation ASCustomSwipeRefreshLayoutImpl

@synthesize uiView = uiView_;

- (void)loadAttributesWithNSString:(NSString *)localName {
  ASViewGroupImpl_register__WithNSString_(localName);
  ASWidgetFactory_registerAttributeWithNSString_withASWidgetAttribute_Builder_(localName, [((ASWidgetAttribute_Builder *) nil_chk([new_ASWidgetAttribute_Builder_init() withNameWithNSString:@"customHeadLayout"])) withTypeWithNSString:@"string"]);
  ASConverterFactory_register__WithNSString_withASIConverter_(@"com.reginald.swiperefresh.CustomSwipeRefreshLayout.refreshMode", new_ASCustomSwipeRefreshLayoutImpl_RefreshMode_init());
  ASWidgetFactory_registerAttributeWithNSString_withASWidgetAttribute_Builder_(localName, [((ASWidgetAttribute_Builder *) nil_chk([new_ASWidgetAttribute_Builder_init() withNameWithNSString:@"refresh_mode"])) withTypeWithNSString:@"com.reginald.swiperefresh.CustomSwipeRefreshLayout.refreshMode"]);
  ASWidgetFactory_registerAttributeWithNSString_withASWidgetAttribute_Builder_(localName, [((ASWidgetAttribute_Builder *) nil_chk([new_ASWidgetAttribute_Builder_init() withNameWithNSString:@"onRefresh"])) withTypeWithNSString:@"string"]);
  ASWidgetFactory_registerAttributeWithNSString_withASWidgetAttribute_Builder_(localName, [((ASWidgetAttribute_Builder *) nil_chk([new_ASWidgetAttribute_Builder_init() withNameWithNSString:@"enableHorizontalScroll"])) withTypeWithNSString:@"boolean"]);
  ASWidgetFactory_registerAttributeWithNSString_withASWidgetAttribute_Builder_(localName, [((ASWidgetAttribute_Builder *) nil_chk([new_ASWidgetAttribute_Builder_init() withNameWithNSString:@"enable_top_progress_bar"])) withTypeWithNSString:@"boolean"]);
  ASWidgetFactory_registerAttributeWithNSString_withASWidgetAttribute_Builder_(localName, [((ASWidgetAttribute_Builder *) nil_chk([new_ASWidgetAttribute_Builder_init() withNameWithNSString:@"keep_refresh_head"])) withTypeWithNSString:@"boolean"]);
  ASWidgetFactory_registerAttributeWithNSString_withASWidgetAttribute_Builder_(localName, [((ASWidgetAttribute_Builder *) nil_chk([new_ASWidgetAttribute_Builder_init() withNameWithNSString:@"return_to_top_duration"])) withTypeWithNSString:@"int"]);
  ASWidgetFactory_registerAttributeWithNSString_withASWidgetAttribute_Builder_(localName, [((ASWidgetAttribute_Builder *) nil_chk([new_ASWidgetAttribute_Builder_init() withNameWithNSString:@"return_to_header_duration"])) withTypeWithNSString:@"int"]);
  ASWidgetFactory_registerAttributeWithNSString_withASWidgetAttribute_Builder_(localName, [((ASWidgetAttribute_Builder *) nil_chk([new_ASWidgetAttribute_Builder_init() withNameWithNSString:@"resistanceFactor"])) withTypeWithNSString:@"float"]);
  ASWidgetFactory_registerAttributeWithNSString_withASWidgetAttribute_Builder_(localName, [((ASWidgetAttribute_Builder *) nil_chk([new_ASWidgetAttribute_Builder_init() withNameWithNSString:@"progressBarHeight"])) withTypeWithNSString:@"dimension"]);
  ASWidgetFactory_registerAttributeWithNSString_withASWidgetAttribute_Builder_(localName, [((ASWidgetAttribute_Builder *) nil_chk([new_ASWidgetAttribute_Builder_init() withNameWithNSString:@"triggerDistance"])) withTypeWithNSString:@"int"]);
  ASWidgetFactory_registerAttributeWithNSString_withASWidgetAttribute_Builder_(localName, [((ASWidgetAttribute_Builder *) nil_chk([new_ASWidgetAttribute_Builder_init() withNameWithNSString:@"top_progress_bar_color_scheme"])) withTypeWithNSString:@"resourcestring"]);
}

J2OBJC_IGNORE_DESIGNATED_BEGIN
- (instancetype)init {
  ASCustomSwipeRefreshLayoutImpl_init(self);
  return self;
}
J2OBJC_IGNORE_DESIGNATED_END

- (instancetype)initWithNSString:(NSString *)localname {
  ASCustomSwipeRefreshLayoutImpl_initWithNSString_(self, localname);
  return self;
}

- (instancetype)initWithNSString:(NSString *)groupName
                    withNSString:(NSString *)localname {
  ASCustomSwipeRefreshLayoutImpl_initWithNSString_withNSString_(self, groupName, localname);
  return self;
}

- (id<ASIWidget>)newInstance {
  return new_ASCustomSwipeRefreshLayoutImpl_initWithNSString_withNSString_(groupName_, localName_);
}

- (void)createWithASIFragment:(id<ASIFragment>)fragment
              withJavaUtilMap:(id<JavaUtilMap>)params {
  [super createWithASIFragment:fragment withJavaUtilMap:params];
  customSwipeRefreshLayout_ = new_ASCustomSwipeRefreshLayoutImpl_CustomSwipeRefreshLayoutExt_initWithASCustomSwipeRefreshLayoutImpl_(self);
  [self nativeCreateWithJavaUtilMap:params];
  ASViewGroupImpl_registerCommandConveterWithASIWidget_(self);
  ASCustomSwipeRefreshLayoutImpl_setWidgetOnNativeClass(self);
}

- (void)setWidgetOnNativeClass {
  ASCustomSwipeRefreshLayoutImpl_setWidgetOnNativeClass(self);
}

- (id)asWidget {
  return customSwipeRefreshLayout_;
}

- (bool)removeWithASIWidget:(id<ASIWidget>)w {
  bool remove = [super removeWithASIWidget:w];
  [((ASCustomSwipeRefreshLayout *) nil_chk(customSwipeRefreshLayout_)) removeViewWithADView:(ADView *) cast_chk([((id<ASIWidget>) nil_chk(w)) asWidget], [ADView class])];
  ASCustomSwipeRefreshLayoutImpl_nativeRemoveViewWithASIWidget_(self, w);
  return remove;
}

- (bool)removeWithInt:(int32_t)index {
  id<ASIWidget> widget = [((id<JavaUtilList>) nil_chk(widgets_)) getWithInt:index];
  bool remove = [super removeWithInt:index];
  if (index + 1 <= [((ASCustomSwipeRefreshLayout *) nil_chk(customSwipeRefreshLayout_)) getChildCount]) {
    [((ASCustomSwipeRefreshLayout *) nil_chk(customSwipeRefreshLayout_)) removeViewAtWithInt:index];
    ASCustomSwipeRefreshLayoutImpl_nativeRemoveViewWithASIWidget_(self, widget);
  }
  return remove;
}

- (void)nativeRemoveViewWithASIWidget:(id<ASIWidget>)widget {
  ASCustomSwipeRefreshLayoutImpl_nativeRemoveViewWithASIWidget_(self, widget);
}

- (void)addWithASIWidget:(id<ASIWidget>)w
                 withInt:(int32_t)index {
  if (index != -2) {
    ADView *view = (ADView *) cast_chk([((id<ASIWidget>) nil_chk(w)) asWidget], [ADView class]);
    ASCustomSwipeRefreshLayoutImpl_createLayoutParamsWithADView_(self, view);
    if (index == -1) {
      [((ASCustomSwipeRefreshLayout *) nil_chk(customSwipeRefreshLayout_)) addViewWithADView:view];
    }
    else {
      [((ASCustomSwipeRefreshLayout *) nil_chk(customSwipeRefreshLayout_)) addViewWithADView:view withInt:index];
    }
  }
  ASViewGroupImpl_nativeAddViewWithId_withId_([self asNativeWidget], [((id<ASIWidget>) nil_chk(w)) asNativeWidget]);
  [super addWithASIWidget:w withInt:index];
}

- (void)createLayoutParamsWithADView:(ADView *)view {
  ASCustomSwipeRefreshLayoutImpl_createLayoutParamsWithADView_(self, view);
}

- (ASCustomSwipeRefreshLayout_LayoutParams *)getLayoutParamsWithADView:(ADView *)view {
  return ASCustomSwipeRefreshLayoutImpl_getLayoutParamsWithADView_(self, view);
}

- (void)setChildAttributeWithASIWidget:(id<ASIWidget>)w
                 withASWidgetAttribute:(ASWidgetAttribute *)key
                          withNSString:(NSString *)strValue
                                withId:(id)objValue {
  ADView *view = (ADView *) cast_chk([((id<ASIWidget>) nil_chk(w)) asWidget], [ADView class]);
  ASCustomSwipeRefreshLayout_LayoutParams *layoutParams = ASCustomSwipeRefreshLayoutImpl_getLayoutParamsWithADView_(self, view);
  ASViewGroupImpl_setChildAttributeWithASIWidget_withASWidgetAttribute_withId_withId_(w, key, objValue, layoutParams);
  switch (JreIndexOfStr([((ASWidgetAttribute *) nil_chk(key)) getAttributeName], (id[]){ @"layout_width", @"layout_height" }, 2)) {
    case 0:
    ((ASCustomSwipeRefreshLayout_LayoutParams *) nil_chk(layoutParams))->width_ = [((JavaLangInteger *) nil_chk((JavaLangInteger *) cast_chk(objValue, [JavaLangInteger class]))) intValue];
    break;
    case 1:
    ((ASCustomSwipeRefreshLayout_LayoutParams *) nil_chk(layoutParams))->height_ = [((JavaLangInteger *) nil_chk((JavaLangInteger *) cast_chk(objValue, [JavaLangInteger class]))) intValue];
    break;
    default:
    break;
  }
  [((ADView *) nil_chk(view)) setLayoutParamsWithADViewGroup_LayoutParams:layoutParams];
}

- (id)getChildAttributeWithASIWidget:(id<ASIWidget>)w
               withASWidgetAttribute:(ASWidgetAttribute *)key {
  id attributeValue = ASViewGroupImpl_getChildAttributeWithASIWidget_withASWidgetAttribute_(w, key);
  if (attributeValue != nil) {
    return attributeValue;
  }
  ADView *view = (ADView *) cast_chk([((id<ASIWidget>) nil_chk(w)) asWidget], [ADView class]);
  ASCustomSwipeRefreshLayout_LayoutParams *layoutParams = ASCustomSwipeRefreshLayoutImpl_getLayoutParamsWithADView_(self, view);
  switch (JreIndexOfStr([((ASWidgetAttribute *) nil_chk(key)) getAttributeName], (id[]){ @"layout_width", @"layout_height" }, 2)) {
    case 0:
    return JavaLangInteger_valueOfWithInt_(((ASCustomSwipeRefreshLayout_LayoutParams *) nil_chk(layoutParams))->width_);
    case 1:
    return JavaLangInteger_valueOfWithInt_(((ASCustomSwipeRefreshLayout_LayoutParams *) nil_chk(layoutParams))->height_);
  }
  return nil;
}

- (IOSClass *)getViewClass {
  return ASCustomSwipeRefreshLayoutImpl_CustomSwipeRefreshLayoutExt_class_();
}

- (void)setAttributeWithASWidgetAttribute:(ASWidgetAttribute *)key
                             withNSString:(NSString *)strValue
                                   withId:(id)objValue
                withASILifeCycleDecorator:(id<ASILifeCycleDecorator>)decorator {
  ASViewGroupImpl_setAttributeWithASIWidget_withASWidgetAttribute_withNSString_withId_withASILifeCycleDecorator_(self, key, strValue, objValue, decorator);
  id nativeWidget = [self asNativeWidget];
  switch (JreIndexOfStr([((ASWidgetAttribute *) nil_chk(key)) getAttributeName], (id[]){ @"customHeadLayout", @"refresh_mode", @"onRefresh", @"enableHorizontalScroll", @"enable_top_progress_bar", @"keep_refresh_head", @"return_to_top_duration", @"return_to_header_duration", @"resistanceFactor", @"progressBarHeight", @"triggerDistance", @"top_progress_bar_color_scheme" }, 12)) {
    case 0:
    {
      ASCustomSwipeRefreshLayoutImpl_setCustomHeadLayoutWithId_(self, objValue);
    }
    break;
    case 1:
    {
      [((ASCustomSwipeRefreshLayout *) nil_chk(customSwipeRefreshLayout_)) setRefreshModeWithInt:[((JavaLangInteger *) nil_chk((JavaLangInteger *) cast_chk(objValue, [JavaLangInteger class]))) intValue]];
    }
    break;
    case 2:
    {
      [((ASCustomSwipeRefreshLayout *) nil_chk(customSwipeRefreshLayout_)) setOnRefreshListenerWithASCustomSwipeRefreshLayout_OnRefreshListener:new_ASCustomSwipeRefreshLayoutImpl_OnRefreshListener_initWithASIWidget_withNSString_withNSString_(self, strValue, @"onRefresh")];
    }
    break;
    case 3:
    {
      [((ASCustomSwipeRefreshLayout *) nil_chk(customSwipeRefreshLayout_)) setEnableHorizontalScrollWithBoolean:[((JavaLangBoolean *) nil_chk((JavaLangBoolean *) cast_chk(objValue, [JavaLangBoolean class]))) booleanValue]];
    }
    break;
    case 4:
    {
      [((ASCustomSwipeRefreshLayout *) nil_chk(customSwipeRefreshLayout_)) enableTopProgressBarWithBoolean:[((JavaLangBoolean *) nil_chk((JavaLangBoolean *) cast_chk(objValue, [JavaLangBoolean class]))) booleanValue]];
    }
    break;
    case 5:
    {
      [((ASCustomSwipeRefreshLayout *) nil_chk(customSwipeRefreshLayout_)) setKeepTopRefreshingHeadWithBoolean:[((JavaLangBoolean *) nil_chk((JavaLangBoolean *) cast_chk(objValue, [JavaLangBoolean class]))) booleanValue]];
    }
    break;
    case 6:
    {
      [((ASCustomSwipeRefreshLayout *) nil_chk(customSwipeRefreshLayout_)) setReturnToTopDurationWithInt:[((JavaLangInteger *) nil_chk((JavaLangInteger *) cast_chk(objValue, [JavaLangInteger class]))) intValue]];
    }
    break;
    case 7:
    {
      [((ASCustomSwipeRefreshLayout *) nil_chk(customSwipeRefreshLayout_)) setReturnToHeaderDurationWithInt:[((JavaLangInteger *) nil_chk((JavaLangInteger *) cast_chk(objValue, [JavaLangInteger class]))) intValue]];
    }
    break;
    case 8:
    {
      [((ASCustomSwipeRefreshLayout *) nil_chk(customSwipeRefreshLayout_)) setResistanceFactorWithFloat:[((JavaLangFloat *) nil_chk((JavaLangFloat *) cast_chk(objValue, [JavaLangFloat class]))) floatValue]];
    }
    break;
    case 9:
    {
      [((ASCustomSwipeRefreshLayout *) nil_chk(customSwipeRefreshLayout_)) setProgressBarHeightWithInt:[((JavaLangInteger *) nil_chk((JavaLangInteger *) cast_chk(objValue, [JavaLangInteger class]))) intValue]];
    }
    break;
    case 10:
    {
      [((ASCustomSwipeRefreshLayout *) nil_chk(customSwipeRefreshLayout_)) setTriggerDistanceWithInt:[((JavaLangInteger *) nil_chk((JavaLangInteger *) cast_chk(objValue, [JavaLangInteger class]))) intValue]];
    }
    break;
    case 11:
    {
      ASCustomSwipeRefreshLayoutImpl_setTopProgressBarColorSchemeWithId_(self, objValue);
    }
    break;
    default:
    break;
  }
}

- (id)getAttributeWithASWidgetAttribute:(ASWidgetAttribute *)key
              withASILifeCycleDecorator:(id<ASILifeCycleDecorator>)decorator {
  id attributeValue = ASViewGroupImpl_getAttributeWithASIWidget_withASWidgetAttribute_withASILifeCycleDecorator_(self, key, decorator);
  if (attributeValue != nil) {
    return attributeValue;
  }
  id nativeWidget = [self asNativeWidget];
  switch (JreIndexOfStr([((ASWidgetAttribute *) nil_chk(key)) getAttributeName], (id[]){  }, 0)) {
  }
  return nil;
}

- (id)asNativeWidget {
  return uiView_;
}

- (bool)checkIosVersionWithNSString:(NSString *)v {
  return ([[[UIDevice currentDevice] systemVersion] compare:v options:NSNumericSearch] == NSOrderedDescending);
}

- (void)nativeCreateWithJavaUtilMap:(id<JavaUtilMap>)params {
  ASUIView* uiView = [ASUIView new];
  uiView.backgroundColor = [UIColor clearColor];
  uiView_ = uiView;
}

- (void)requestLayout {
  if ([self isInitialised]) {
    ASViewImpl_requestLayoutWithASIWidget_withId_(self, [self asNativeWidget]);
  }
}

- (void)invalidate {
  if ([self isInitialised]) {
    ASViewImpl_invalidateWithASIWidget_withId_(self, [self asNativeWidget]);
  }
}

- (void)setCustomHeadLayoutWithId:(id)objValue {
  ASCustomSwipeRefreshLayoutImpl_setCustomHeadLayoutWithId_(self, objValue);
}

- (void)setTopProgressBarColorSchemeWithId:(id)objValue {
  ASCustomSwipeRefreshLayoutImpl_setTopProgressBarColorSchemeWithId_(self, objValue);
}

- (void)setIdWithNSString:(NSString *)id_ {
  if (id_ != nil && ![id_ isEqual:@""]) {
    [super setIdWithNSString:id_];
    [((ASCustomSwipeRefreshLayout *) nil_chk(customSwipeRefreshLayout_)) setIdWithInt:[((JavaLangInteger *) nil_chk((JavaLangInteger *) cast_chk([self quickConvertWithId:id_ withNSString:@"id"], [JavaLangInteger class]))) intValue]];
  }
}

- (void)setVisibleWithBoolean:(bool)b {
  [((ADView *) nil_chk(((ADView *) cast_chk([self asWidget], [ADView class])))) setVisibilityWithInt:b ? ADView_VISIBLE : ADView_GONE];
}

- (void)initialized {
  [super initialized];
  ASViewImpl_addPanListenerWithASIWidget_withId_withId_withASViewImpl_PanCallBack_(self, [self asNativeWidget], uiView_, new_ASCustomSwipeRefreshLayoutImpl_1_initWithASCustomSwipeRefreshLayoutImpl_(self));
}

- (bool)processTouchEventWithInt:(int32_t)action
                         withInt:(int32_t)x
                         withInt:(int32_t)y {
  return ASCustomSwipeRefreshLayoutImpl_processTouchEventWithInt_withInt_withInt_(self, action, x, y);
}

+ (const J2ObjcClassInfo *)__metadata {
  static J2ObjcMethodInfo methods[] = {
    { NULL, "V", 0x1, 0, 1, -1, -1, -1, -1 },
    { NULL, NULL, 0x1, -1, -1, -1, -1, -1, -1 },
    { NULL, NULL, 0x1, -1, 1, -1, -1, -1, -1 },
    { NULL, NULL, 0x1, -1, 2, -1, -1, -1, -1 },
    { NULL, "LASIWidget;", 0x1, -1, -1, -1, -1, -1, -1 },
    { NULL, "V", 0x1, 3, 4, -1, 5, -1, -1 },
    { NULL, "V", 0x102, -1, -1, -1, -1, -1, -1 },
    { NULL, "LNSObject;", 0x1, -1, -1, -1, -1, -1, -1 },
    { NULL, "Z", 0x1, 6, 7, -1, -1, -1, -1 },
    { NULL, "Z", 0x1, 6, 8, -1, -1, -1, -1 },
    { NULL, "V", 0x2, 9, 7, -1, -1, -1, -1 },
    { NULL, "V", 0x1, 10, 11, -1, -1, -1, -1 },
    { NULL, "V", 0x2, 12, 13, -1, -1, -1, -1 },
    { NULL, "LASCustomSwipeRefreshLayout_LayoutParams;", 0x2, 14, 13, -1, -1, -1, -1 },
    { NULL, "V", 0x1, 15, 16, -1, -1, -1, -1 },
    { NULL, "LNSObject;", 0x1, 17, 18, -1, -1, -1, -1 },
    { NULL, "LIOSClass;", 0x1, -1, -1, -1, -1, -1, -1 },
    { NULL, "V", 0x1, 19, 20, -1, -1, -1, -1 },
    { NULL, "LNSObject;", 0x1, 21, 22, -1, -1, -1, -1 },
    { NULL, "LNSObject;", 0x1, -1, -1, -1, -1, -1, -1 },
    { NULL, "Z", 0x101, 23, 1, -1, -1, -1, -1 },
    { NULL, "V", 0x101, 24, 25, -1, 26, -1, -1 },
    { NULL, "V", 0x1, -1, -1, -1, -1, -1, -1 },
    { NULL, "V", 0x1, -1, -1, -1, -1, -1, -1 },
    { NULL, "V", 0x2, 27, 28, -1, -1, -1, -1 },
    { NULL, "V", 0x2, 29, 28, -1, -1, -1, -1 },
    { NULL, "V", 0x1, 30, 1, -1, -1, -1, -1 },
    { NULL, "V", 0x1, 31, 32, -1, -1, -1, -1 },
    { NULL, "V", 0x1, -1, -1, -1, -1, -1, -1 },
    { NULL, "Z", 0x2, 33, 34, -1, -1, -1, -1 },
  };
  #pragma clang diagnostic push
  #pragma clang diagnostic ignored "-Wobjc-multiple-method-names"
  #pragma clang diagnostic ignored "-Wundeclared-selector"
  methods[0].selector = @selector(loadAttributesWithNSString:);
  methods[1].selector = @selector(init);
  methods[2].selector = @selector(initWithNSString:);
  methods[3].selector = @selector(initWithNSString:withNSString:);
  methods[4].selector = @selector(newInstance);
  methods[5].selector = @selector(createWithASIFragment:withJavaUtilMap:);
  methods[6].selector = @selector(setWidgetOnNativeClass);
  methods[7].selector = @selector(asWidget);
  methods[8].selector = @selector(removeWithASIWidget:);
  methods[9].selector = @selector(removeWithInt:);
  methods[10].selector = @selector(nativeRemoveViewWithASIWidget:);
  methods[11].selector = @selector(addWithASIWidget:withInt:);
  methods[12].selector = @selector(createLayoutParamsWithADView:);
  methods[13].selector = @selector(getLayoutParamsWithADView:);
  methods[14].selector = @selector(setChildAttributeWithASIWidget:withASWidgetAttribute:withNSString:withId:);
  methods[15].selector = @selector(getChildAttributeWithASIWidget:withASWidgetAttribute:);
  methods[16].selector = @selector(getViewClass);
  methods[17].selector = @selector(setAttributeWithASWidgetAttribute:withNSString:withId:withASILifeCycleDecorator:);
  methods[18].selector = @selector(getAttributeWithASWidgetAttribute:withASILifeCycleDecorator:);
  methods[19].selector = @selector(asNativeWidget);
  methods[20].selector = @selector(checkIosVersionWithNSString:);
  methods[21].selector = @selector(nativeCreateWithJavaUtilMap:);
  methods[22].selector = @selector(requestLayout);
  methods[23].selector = @selector(invalidate);
  methods[24].selector = @selector(setCustomHeadLayoutWithId:);
  methods[25].selector = @selector(setTopProgressBarColorSchemeWithId:);
  methods[26].selector = @selector(setIdWithNSString:);
  methods[27].selector = @selector(setVisibleWithBoolean:);
  methods[28].selector = @selector(initialized);
  methods[29].selector = @selector(processTouchEventWithInt:withInt:withInt:);
  #pragma clang diagnostic pop
  static const J2ObjcFieldInfo fields[] = {
    { "uiView_", "LNSObject;", .constantValue.asLong = 0, 0x2, -1, -1, -1, -1 },
    { "LOCAL_NAME", "LNSString;", .constantValue.asLong = 0, 0x19, -1, 35, -1, -1 },
    { "GROUP_NAME", "LNSString;", .constantValue.asLong = 0, 0x19, -1, 36, -1, -1 },
    { "customSwipeRefreshLayout_", "LASCustomSwipeRefreshLayout;", .constantValue.asLong = 0, 0x2, -1, -1, -1, -1 },
    { "action_", "I", .constantValue.asLong = 0, 0x2, -1, -1, -1, -1 },
    { "event_", "LADMotionEvent;", .constantValue.asLong = 0, 0x2, -1, -1, -1, -1 },
  };
  static const void *ptrTable[] = { "loadAttributes", "LNSString;", "LNSString;LNSString;", "create", "LASIFragment;LJavaUtilMap;", "(Lcom/ashera/core/IFragment;Ljava/util/Map<Ljava/lang/String;Ljava/lang/Object;>;)V", "remove", "LASIWidget;", "I", "nativeRemoveView", "add", "LASIWidget;I", "createLayoutParams", "LADView;", "getLayoutParams", "setChildAttribute", "LASIWidget;LASWidgetAttribute;LNSString;LNSObject;", "getChildAttribute", "LASIWidget;LASWidgetAttribute;", "setAttribute", "LASWidgetAttribute;LNSString;LNSObject;LASILifeCycleDecorator;", "getAttribute", "LASWidgetAttribute;LASILifeCycleDecorator;", "checkIosVersion", "nativeCreate", "LJavaUtilMap;", "(Ljava/util/Map<Ljava/lang/String;Ljava/lang/Object;>;)V", "setCustomHeadLayout", "LNSObject;", "setTopProgressBarColorScheme", "setId", "setVisible", "Z", "processTouchEvent", "III", &ASCustomSwipeRefreshLayoutImpl_LOCAL_NAME, &ASCustomSwipeRefreshLayoutImpl_GROUP_NAME, "LASCustomSwipeRefreshLayoutImpl_RefreshMode;LASCustomSwipeRefreshLayoutImpl_CustomSwipeRefreshLayoutExt;LASCustomSwipeRefreshLayoutImpl_OnRefreshListener;" };
  static const J2ObjcClassInfo _ASCustomSwipeRefreshLayoutImpl = { "CustomSwipeRefreshLayoutImpl", "com.ashera.swiperefreshlayout", ptrTable, methods, fields, 7, 0x1, 30, 6, -1, 37, -1, -1, -1 };
  return &_ASCustomSwipeRefreshLayoutImpl;
}

@end

void ASCustomSwipeRefreshLayoutImpl_init(ASCustomSwipeRefreshLayoutImpl *self) {
  ASBaseHasWidgets_initWithNSString_withNSString_(self, ASCustomSwipeRefreshLayoutImpl_GROUP_NAME, ASCustomSwipeRefreshLayoutImpl_LOCAL_NAME);
  self->event_ = new_ADMotionEvent_init();
}

ASCustomSwipeRefreshLayoutImpl *new_ASCustomSwipeRefreshLayoutImpl_init() {
  J2OBJC_NEW_IMPL(ASCustomSwipeRefreshLayoutImpl, init)
}

ASCustomSwipeRefreshLayoutImpl *create_ASCustomSwipeRefreshLayoutImpl_init() {
  J2OBJC_CREATE_IMPL(ASCustomSwipeRefreshLayoutImpl, init)
}

void ASCustomSwipeRefreshLayoutImpl_initWithNSString_(ASCustomSwipeRefreshLayoutImpl *self, NSString *localname) {
  ASBaseHasWidgets_initWithNSString_withNSString_(self, ASCustomSwipeRefreshLayoutImpl_GROUP_NAME, localname);
  self->event_ = new_ADMotionEvent_init();
}

ASCustomSwipeRefreshLayoutImpl *new_ASCustomSwipeRefreshLayoutImpl_initWithNSString_(NSString *localname) {
  J2OBJC_NEW_IMPL(ASCustomSwipeRefreshLayoutImpl, initWithNSString_, localname)
}

ASCustomSwipeRefreshLayoutImpl *create_ASCustomSwipeRefreshLayoutImpl_initWithNSString_(NSString *localname) {
  J2OBJC_CREATE_IMPL(ASCustomSwipeRefreshLayoutImpl, initWithNSString_, localname)
}

void ASCustomSwipeRefreshLayoutImpl_initWithNSString_withNSString_(ASCustomSwipeRefreshLayoutImpl *self, NSString *groupName, NSString *localname) {
  ASBaseHasWidgets_initWithNSString_withNSString_(self, groupName, localname);
  self->event_ = new_ADMotionEvent_init();
}

ASCustomSwipeRefreshLayoutImpl *new_ASCustomSwipeRefreshLayoutImpl_initWithNSString_withNSString_(NSString *groupName, NSString *localname) {
  J2OBJC_NEW_IMPL(ASCustomSwipeRefreshLayoutImpl, initWithNSString_withNSString_, groupName, localname)
}

ASCustomSwipeRefreshLayoutImpl *create_ASCustomSwipeRefreshLayoutImpl_initWithNSString_withNSString_(NSString *groupName, NSString *localname) {
  J2OBJC_CREATE_IMPL(ASCustomSwipeRefreshLayoutImpl, initWithNSString_withNSString_, groupName, localname)
}

void ASCustomSwipeRefreshLayoutImpl_setWidgetOnNativeClass(ASCustomSwipeRefreshLayoutImpl *self) {
  ((ASUIView*) [self asNativeWidget]).widget = self;
}

void ASCustomSwipeRefreshLayoutImpl_nativeRemoveViewWithASIWidget_(ASCustomSwipeRefreshLayoutImpl *self, id<ASIWidget> widget) {
  ADLayoutTransition *layoutTransition = [((ASCustomSwipeRefreshLayout *) nil_chk(self->customSwipeRefreshLayout_)) getLayoutTransition];
  if (layoutTransition != nil && ([layoutTransition isTransitionTypeEnabledWithInt:ADLayoutTransition_CHANGE_DISAPPEARING] || [layoutTransition isTransitionTypeEnabledWithInt:ADLayoutTransition_DISAPPEARING])) {
    [self addToBufferedRunnablesWithJavaLangRunnable:new_ASCustomSwipeRefreshLayoutImpl_$Lambda$1_initWithASIWidget_(widget)];
  }
  else {
    ASViewGroupImpl_nativeRemoveViewWithASIWidget_(widget);
  }
}

void ASCustomSwipeRefreshLayoutImpl_createLayoutParamsWithADView_(ASCustomSwipeRefreshLayoutImpl *self, ADView *view) {
  ASCustomSwipeRefreshLayout_LayoutParams *layoutParams = (ASCustomSwipeRefreshLayout_LayoutParams *) cast_chk([((ADView *) nil_chk(view)) getLayoutParams], [ASCustomSwipeRefreshLayout_LayoutParams class]);
  layoutParams = (ASCustomSwipeRefreshLayout_LayoutParams *) cast_chk([view getLayoutParams], [ASCustomSwipeRefreshLayout_LayoutParams class]);
  if (layoutParams == nil) {
    layoutParams = new_ASCustomSwipeRefreshLayout_LayoutParams_initWithInt_withInt_(-2, -2);
    [view setLayoutParamsWithADViewGroup_LayoutParams:layoutParams];
  }
  else {
    layoutParams->height_ = -2;
    layoutParams->width_ = -2;
  }
}

ASCustomSwipeRefreshLayout_LayoutParams *ASCustomSwipeRefreshLayoutImpl_getLayoutParamsWithADView_(ASCustomSwipeRefreshLayoutImpl *self, ADView *view) {
  return (ASCustomSwipeRefreshLayout_LayoutParams *) cast_chk([((ADView *) nil_chk(view)) getLayoutParams], [ASCustomSwipeRefreshLayout_LayoutParams class]);
}

void ASCustomSwipeRefreshLayoutImpl_setCustomHeadLayoutWithId_(ASCustomSwipeRefreshLayoutImpl *self, id objValue) {
  [((ASCustomSwipeRefreshLayout *) nil_chk(self->customSwipeRefreshLayout_)) setCustomHeaderLayoutWithNSString:(NSString *) cast_chk(objValue, [NSString class])];
}

void ASCustomSwipeRefreshLayoutImpl_setTopProgressBarColorSchemeWithId_(ASCustomSwipeRefreshLayoutImpl *self, id objValue) {
  IOSObjectArray *colorSchemes = [((NSString *) nil_chk(((NSString *) cast_chk(objValue, [NSString class])))) java_split:@","];
  if (((IOSObjectArray *) nil_chk(colorSchemes))->size_ != 4) {
    @throw new_JavaLangRuntimeException_initWithNSString_(JreStrcat("$@$", @"Invalid format ", objValue, @" for color scheme. Example format : #000,#fff,#000,#fff"));
  }
  [((ASCustomSwipeRefreshLayout *) nil_chk(self->customSwipeRefreshLayout_)) setProgressBarColorWithId:[self quickConvertWithId:[((NSString *) nil_chk(IOSObjectArray_Get(colorSchemes, 0))) java_trim] withNSString:@"color"] withId:[self quickConvertWithId:[((NSString *) nil_chk(IOSObjectArray_Get(colorSchemes, 1))) java_trim] withNSString:@"color"] withId:[self quickConvertWithId:[((NSString *) nil_chk(IOSObjectArray_Get(colorSchemes, 2))) java_trim] withNSString:@"color"] withId:[self quickConvertWithId:[((NSString *) nil_chk(IOSObjectArray_Get(colorSchemes, 3))) java_trim] withNSString:@"color"]];
}

bool ASCustomSwipeRefreshLayoutImpl_processTouchEventWithInt_withInt_withInt_(ASCustomSwipeRefreshLayoutImpl *self, int32_t action, int32_t x, int32_t y) {
  [((ADMotionEvent *) nil_chk(self->event_)) setXWithInt:x];
  [((ADMotionEvent *) nil_chk(self->event_)) setYWithInt:y];
  [((ADMotionEvent *) nil_chk(self->event_)) setActionWithInt:action];
  return [((ASCustomSwipeRefreshLayout *) nil_chk(self->customSwipeRefreshLayout_)) onInterceptTouchEventWithADMotionEvent:self->event_];
}

J2OBJC_CLASS_TYPE_LITERAL_SOURCE(ASCustomSwipeRefreshLayoutImpl)

J2OBJC_NAME_MAPPING(ASCustomSwipeRefreshLayoutImpl, "com.ashera.swiperefreshlayout", "AS")

@implementation ASCustomSwipeRefreshLayoutImpl_RefreshMode

J2OBJC_IGNORE_DESIGNATED_BEGIN
- (instancetype)init {
  ASCustomSwipeRefreshLayoutImpl_RefreshMode_init(self);
  return self;
}
J2OBJC_IGNORE_DESIGNATED_END

- (id<JavaUtilMap>)getMapping {
  return mapping_;
}

- (JavaLangInteger *)getDefault {
  return JavaLangInteger_valueOfWithInt_(0);
}

+ (const J2ObjcClassInfo *)__metadata {
  static J2ObjcMethodInfo methods[] = {
    { NULL, NULL, 0x0, -1, -1, -1, -1, -1, -1 },
    { NULL, "LJavaUtilMap;", 0x1, -1, -1, -1, 0, -1, -1 },
    { NULL, "LJavaLangInteger;", 0x1, -1, -1, -1, -1, -1, -1 },
  };
  #pragma clang diagnostic push
  #pragma clang diagnostic ignored "-Wobjc-multiple-method-names"
  #pragma clang diagnostic ignored "-Wundeclared-selector"
  methods[0].selector = @selector(init);
  methods[1].selector = @selector(getMapping);
  methods[2].selector = @selector(getDefault);
  #pragma clang diagnostic pop
  static const J2ObjcFieldInfo fields[] = {
    { "mapping_", "LJavaUtilMap;", .constantValue.asLong = 0, 0x2, -1, -1, 1, -1 },
  };
  static const void *ptrTable[] = { "()Ljava/util/Map<Ljava/lang/String;Ljava/lang/Integer;>;", "Ljava/util/Map<Ljava/lang/String;Ljava/lang/Integer;>;", "LASCustomSwipeRefreshLayoutImpl;" };
  static const J2ObjcClassInfo _ASCustomSwipeRefreshLayoutImpl_RefreshMode = { "RefreshMode", "com.ashera.swiperefreshlayout", ptrTable, methods, fields, 7, 0x18, 3, 1, 2, -1, -1, -1, -1 };
  return &_ASCustomSwipeRefreshLayoutImpl_RefreshMode;
}

@end

void ASCustomSwipeRefreshLayoutImpl_RefreshMode_init(ASCustomSwipeRefreshLayoutImpl_RefreshMode *self) {
  ASAbstractEnumToIntConverter_init(self);
  self->mapping_ = new_JavaUtilHashMap_init();
  {
    (void) [self->mapping_ putWithId:@"swipe_mode" withId:JavaLangInteger_valueOfWithInt_((int32_t) 0x1)];
    (void) [((id<JavaUtilMap>) nil_chk(self->mapping_)) putWithId:@"pull_mode" withId:JavaLangInteger_valueOfWithInt_((int32_t) 0x2)];
  }
}

ASCustomSwipeRefreshLayoutImpl_RefreshMode *new_ASCustomSwipeRefreshLayoutImpl_RefreshMode_init() {
  J2OBJC_NEW_IMPL(ASCustomSwipeRefreshLayoutImpl_RefreshMode, init)
}

ASCustomSwipeRefreshLayoutImpl_RefreshMode *create_ASCustomSwipeRefreshLayoutImpl_RefreshMode_init() {
  J2OBJC_CREATE_IMPL(ASCustomSwipeRefreshLayoutImpl_RefreshMode, init)
}

J2OBJC_CLASS_TYPE_LITERAL_SOURCE(ASCustomSwipeRefreshLayoutImpl_RefreshMode)

@implementation ASCustomSwipeRefreshLayoutImpl_CustomSwipeRefreshLayoutExt

- (id<ASIWidget>)getWidget {
  return this$0_;
}

- (void)setMaxWidthWithInt:(int32_t)width {
  mMaxWidth_ = width;
}

- (void)setMaxHeightWithInt:(int32_t)height {
  mMaxHeight_ = height;
}

- (int32_t)getMaxWidth {
  return mMaxWidth_;
}

- (int32_t)getMaxHeight {
  return mMaxHeight_;
}

- (instancetype)initWithASCustomSwipeRefreshLayoutImpl:(ASCustomSwipeRefreshLayoutImpl *)outer$ {
  ASCustomSwipeRefreshLayoutImpl_CustomSwipeRefreshLayoutExt_initWithASCustomSwipeRefreshLayoutImpl_(self, outer$);
  return self;
}

- (void)onMeasureWithInt:(int32_t)widthMeasureSpec
                 withInt:(int32_t)heightMeasureSpec {
  if (mMaxWidth_ > 0) {
    widthMeasureSpec = ADView_MeasureSpec_makeMeasureSpecWithInt_withInt_(mMaxWidth_, ADView_MeasureSpec_AT_MOST);
  }
  if (mMaxHeight_ > 0) {
    heightMeasureSpec = ADView_MeasureSpec_makeMeasureSpecWithInt_withInt_(mMaxHeight_, ADView_MeasureSpec_AT_MOST);
  }
  [super onMeasureWithInt:widthMeasureSpec withInt:heightMeasureSpec];
  id<ASIWidgetLifeCycleListener> listener = [this$0_ getListener];
  if (listener != nil) {
    [((ASMeasureEvent *) nil_chk(measureFinished_)) setWidthWithInt:[self getMeasuredWidth]];
    [((ASMeasureEvent *) nil_chk(measureFinished_)) setHeightWithInt:[self getMeasuredHeight]];
    [listener eventOccurredWithASIWidgetLifeCycleListener_EventId:JreLoadEnum(ASIWidgetLifeCycleListener_EventId, measureFinished) withASWidgetEvent:measureFinished_];
  }
}

- (void)onLayoutWithBoolean:(bool)changed
                    withInt:(int32_t)l
                    withInt:(int32_t)t
                    withInt:(int32_t)r
                    withInt:(int32_t)b {
  [super onLayoutWithBoolean:changed withInt:l withInt:t withInt:r withInt:b];
  ASViewImpl_setDrawableBoundsWithASIWidget_withInt_withInt_withInt_withInt_(this$0_, l, t, r, b);
  if (![self isOverlay]) {
    ASViewImpl_nativeMakeFrameWithId_withInt_withInt_withInt_withInt_([this$0_ asNativeWidget], l, t, r, b);
  }
  [this$0_ replayBufferedEvents];
  ASViewImpl_redrawDrawablesWithASIWidget_(this$0_);
  overlays_ = ASViewImpl_drawOverlayWithASIWidget_withJavaUtilList_(this$0_, overlays_);
  id<ASIWidgetLifeCycleListener> listener = [this$0_ getListener];
  if (listener != nil) {
    [((ASOnLayoutEvent *) nil_chk(onLayoutEvent_)) setBWithInt:b];
    [((ASOnLayoutEvent *) nil_chk(onLayoutEvent_)) setLWithInt:l];
    [((ASOnLayoutEvent *) nil_chk(onLayoutEvent_)) setRWithInt:r];
    [((ASOnLayoutEvent *) nil_chk(onLayoutEvent_)) setTWithInt:t];
    [((ASOnLayoutEvent *) nil_chk(onLayoutEvent_)) setChangedWithBoolean:changed];
    [listener eventOccurredWithASIWidgetLifeCycleListener_EventId:JreLoadEnum(ASIWidgetLifeCycleListener_EventId, onLayout) withASWidgetEvent:onLayoutEvent_];
  }
  if ([this$0_ isInvalidateOnFrameChange] && [this$0_ isInitialised]) {
    [this$0_ invalidate];
  }
}

- (void)executeWithNSString:(NSString *)method
          withNSObjectArray:(IOSObjectArray *)canvas {
}

- (void)updateMeasuredDimensionWithInt:(int32_t)width
                               withInt:(int32_t)height {
  [self setMeasuredDimensionWithInt:width withInt:height];
}

- (id<ASILifeCycleDecorator>)newInstanceWithASIWidget:(id<ASIWidget>)widget {
  @throw new_JavaLangUnsupportedOperationException_init();
}

- (void)setAttributeWithASWidgetAttribute:(ASWidgetAttribute *)widgetAttribute
                             withNSString:(NSString *)strValue
                                   withId:(id)objValue {
  @throw new_JavaLangUnsupportedOperationException_init();
}

- (id<JavaUtilList>)getMethods {
  @throw new_JavaLangUnsupportedOperationException_init();
}

- (void)initialized {
  @throw new_JavaLangUnsupportedOperationException_init();
}

- (id)getAttributeWithASWidgetAttribute:(ASWidgetAttribute *)widgetAttribute {
  @throw new_JavaLangUnsupportedOperationException_init();
}

- (void)drawableStateChanged {
  [super drawableStateChanged];
  if (![this$0_ isWidgetDisposed]) {
    ASViewImpl_drawableStateChangedWithASIWidget_(this$0_);
  }
}

- (ADView *)inflateViewWithNSString:(NSString *)layout {
  if (templates_ == nil) {
    templates_ = new_JavaUtilHashMap_init();
  }
  id<ASIWidget> template_ = [templates_ getWithId:layout];
  if (template_ == nil) {
    template_ = (id<ASIWidget>) cast_check([this$0_ quickConvertWithId:layout withNSString:@"template"], ASIWidget_class_());
    (void) [((id<JavaUtilMap>) nil_chk(templates_)) putWithId:layout withId:template_];
  }
  id<ASIWidget> widget = [((id<ASIWidget>) nil_chk(template_)) loadLazyWidgetsWithASHasWidgets:this$0_];
  return (ADView *) cast_chk([((id<ASIWidget>) nil_chk(widget)) asWidget], [ADView class]);
}

- (void)remeasure {
  if ([this$0_ getFragment] != nil) {
    [((id<ASIFragment>) nil_chk([this$0_ getFragment])) remeasure];
  }
}

- (void)removeFromParent {
  [((id<ASHasWidgets>) nil_chk([this$0_ getParent])) removeWithASIWidget:this$0_];
}

- (void)getLocationOnScreenWithIntArray:(IOSIntArray *)appScreenLocation {
  *IOSIntArray_GetRef(nil_chk(appScreenLocation), 0) = ASViewImpl_getLocationXOnScreenWithId_([this$0_ asNativeWidget]);
  *IOSIntArray_GetRef(appScreenLocation, 1) = ASViewImpl_getLocationYOnScreenWithId_([this$0_ asNativeWidget]);
}

- (void)getWindowVisibleDisplayFrameWithADRect:(ADRect *)displayFrame {
  ((ADRect *) nil_chk(displayFrame))->left_ = ASViewImpl_getLocationXOnScreenWithId_([this$0_ asNativeWidget]);
  displayFrame->top_ = ASViewImpl_getLocationYOnScreenWithId_([this$0_ asNativeWidget]);
  displayFrame->right_ = displayFrame->left_ + [self getWidth];
  displayFrame->bottom_ = displayFrame->top_ + [self getHeight];
}

- (void)offsetTopAndBottomWithInt:(int32_t)offset {
  [super offsetTopAndBottomWithInt:offset];
  ASViewImpl_nativeMakeFrameWithId_withInt_withInt_withInt_withInt_([this$0_ asNativeWidget], [self getLeft], [self getTop], [self getRight], [self getBottom]);
}

- (void)offsetLeftAndRightWithInt:(int32_t)offset {
  [super offsetLeftAndRightWithInt:offset];
  ASViewImpl_nativeMakeFrameWithId_withInt_withInt_withInt_withInt_([this$0_ asNativeWidget], [self getLeft], [self getTop], [self getRight], [self getBottom]);
}

- (void)setMyAttributeWithNSString:(NSString *)name
                            withId:(id)value {
  if ([((NSString *) nil_chk(name)) isEqual:@"state0"]) {
    [self setState0WithId:value];
    return;
  }
  if ([name isEqual:@"state1"]) {
    [self setState1WithId:value];
    return;
  }
  if ([name isEqual:@"state2"]) {
    [self setState2WithId:value];
    return;
  }
  if ([name isEqual:@"state3"]) {
    [self setState3WithId:value];
    return;
  }
  if ([name isEqual:@"state4"]) {
    [self setState4WithId:value];
    return;
  }
  [this$0_ setAttributeWithNSString:name withId:value withBoolean:!([value isKindOfClass:[NSString class]])];
}

- (void)setVisibilityWithInt:(int32_t)visibility {
  [super setVisibilityWithInt:visibility];
  ASViewImpl_nativeSetVisibilityWithId_withBoolean_([this$0_ asNativeWidget], visibility != ADView_VISIBLE);
}

- (void)setState0WithId:(id)value {
  ASViewImpl_setStateWithASIWidget_withInt_withId_(this$0_, 0, value);
}

- (void)setState1WithId:(id)value {
  ASViewImpl_setStateWithASIWidget_withInt_withId_(this$0_, 1, value);
}

- (void)setState2WithId:(id)value {
  ASViewImpl_setStateWithASIWidget_withInt_withId_(this$0_, 2, value);
}

- (void)setState3WithId:(id)value {
  ASViewImpl_setStateWithASIWidget_withInt_withId_(this$0_, 3, value);
}

- (void)setState4WithId:(id)value {
  ASViewImpl_setStateWithASIWidget_withInt_withId_(this$0_, 4, value);
}

- (void)state0 {
  ASViewImpl_stateWithASIWidget_withInt_(this$0_, 0);
}

- (void)state1 {
  ASViewImpl_stateWithASIWidget_withInt_(this$0_, 1);
}

- (void)state2 {
  ASViewImpl_stateWithASIWidget_withInt_(this$0_, 2);
}

- (void)state3 {
  ASViewImpl_stateWithASIWidget_withInt_(this$0_, 3);
}

- (void)state4 {
  ASViewImpl_stateWithASIWidget_withInt_(this$0_, 4);
}

- (void)stateYes {
  ASViewImpl_stateYesWithASIWidget_(this$0_);
}

- (void)stateNo {
  ASViewImpl_stateNoWithASIWidget_(this$0_);
}

- (void)endViewTransitionWithADView:(ADView *)view {
  [super endViewTransitionWithADView:view];
  [this$0_ runBufferedRunnables];
}

- (void)__javaClone:(ASCustomSwipeRefreshLayoutImpl_CustomSwipeRefreshLayoutExt *)original {
  [super __javaClone:original];
  JreRelease(this$0_);
}

+ (const J2ObjcClassInfo *)__metadata {
  static J2ObjcMethodInfo methods[] = {
    { NULL, "LASIWidget;", 0x1, -1, -1, -1, -1, -1, -1 },
    { NULL, "V", 0x1, 0, 1, -1, -1, -1, -1 },
    { NULL, "V", 0x1, 2, 1, -1, -1, -1, -1 },
    { NULL, "I", 0x1, -1, -1, -1, -1, -1, -1 },
    { NULL, "I", 0x1, -1, -1, -1, -1, -1, -1 },
    { NULL, NULL, 0x1, -1, 3, -1, -1, -1, -1 },
    { NULL, "V", 0x1, 4, 5, -1, -1, -1, -1 },
    { NULL, "V", 0x4, 6, 7, -1, -1, -1, -1 },
    { NULL, "V", 0x81, 8, 9, -1, -1, -1, -1 },
    { NULL, "V", 0x1, 10, 5, -1, -1, -1, -1 },
    { NULL, "LASILifeCycleDecorator;", 0x1, 11, 12, -1, -1, -1, -1 },
    { NULL, "V", 0x1, 13, 14, -1, -1, -1, -1 },
    { NULL, "LJavaUtilList;", 0x1, -1, -1, -1, 15, -1, -1 },
    { NULL, "V", 0x1, -1, -1, -1, -1, -1, -1 },
    { NULL, "LNSObject;", 0x1, 16, 17, -1, -1, -1, -1 },
    { NULL, "V", 0x1, -1, -1, -1, -1, -1, -1 },
    { NULL, "LADView;", 0x1, 18, 19, -1, -1, -1, -1 },
    { NULL, "V", 0x1, -1, -1, -1, -1, -1, -1 },
    { NULL, "V", 0x1, -1, -1, -1, -1, -1, -1 },
    { NULL, "V", 0x1, 20, 21, -1, -1, -1, -1 },
    { NULL, "V", 0x1, 22, 23, -1, -1, -1, -1 },
    { NULL, "V", 0x1, 24, 1, -1, -1, -1, -1 },
    { NULL, "V", 0x1, 25, 1, -1, -1, -1, -1 },
    { NULL, "V", 0x1, 26, 27, -1, -1, -1, -1 },
    { NULL, "V", 0x1, 28, 1, -1, -1, -1, -1 },
    { NULL, "V", 0x1, 29, 30, -1, -1, -1, -1 },
    { NULL, "V", 0x1, 31, 30, -1, -1, -1, -1 },
    { NULL, "V", 0x1, 32, 30, -1, -1, -1, -1 },
    { NULL, "V", 0x1, 33, 30, -1, -1, -1, -1 },
    { NULL, "V", 0x1, 34, 30, -1, -1, -1, -1 },
    { NULL, "V", 0x1, -1, -1, -1, -1, -1, -1 },
    { NULL, "V", 0x1, -1, -1, -1, -1, -1, -1 },
    { NULL, "V", 0x1, -1, -1, -1, -1, -1, -1 },
    { NULL, "V", 0x1, -1, -1, -1, -1, -1, -1 },
    { NULL, "V", 0x1, -1, -1, -1, -1, -1, -1 },
    { NULL, "V", 0x1, -1, -1, -1, -1, -1, -1 },
    { NULL, "V", 0x1, -1, -1, -1, -1, -1, -1 },
    { NULL, "V", 0x1, 35, 36, -1, -1, -1, -1 },
  };
  #pragma clang diagnostic push
  #pragma clang diagnostic ignored "-Wobjc-multiple-method-names"
  #pragma clang diagnostic ignored "-Wundeclared-selector"
  methods[0].selector = @selector(getWidget);
  methods[1].selector = @selector(setMaxWidthWithInt:);
  methods[2].selector = @selector(setMaxHeightWithInt:);
  methods[3].selector = @selector(getMaxWidth);
  methods[4].selector = @selector(getMaxHeight);
  methods[5].selector = @selector(initWithASCustomSwipeRefreshLayoutImpl:);
  methods[6].selector = @selector(onMeasureWithInt:withInt:);
  methods[7].selector = @selector(onLayoutWithBoolean:withInt:withInt:withInt:withInt:);
  methods[8].selector = @selector(executeWithNSString:withNSObjectArray:);
  methods[9].selector = @selector(updateMeasuredDimensionWithInt:withInt:);
  methods[10].selector = @selector(newInstanceWithASIWidget:);
  methods[11].selector = @selector(setAttributeWithASWidgetAttribute:withNSString:withId:);
  methods[12].selector = @selector(getMethods);
  methods[13].selector = @selector(initialized);
  methods[14].selector = @selector(getAttributeWithASWidgetAttribute:);
  methods[15].selector = @selector(drawableStateChanged);
  methods[16].selector = @selector(inflateViewWithNSString:);
  methods[17].selector = @selector(remeasure);
  methods[18].selector = @selector(removeFromParent);
  methods[19].selector = @selector(getLocationOnScreenWithIntArray:);
  methods[20].selector = @selector(getWindowVisibleDisplayFrameWithADRect:);
  methods[21].selector = @selector(offsetTopAndBottomWithInt:);
  methods[22].selector = @selector(offsetLeftAndRightWithInt:);
  methods[23].selector = @selector(setMyAttributeWithNSString:withId:);
  methods[24].selector = @selector(setVisibilityWithInt:);
  methods[25].selector = @selector(setState0WithId:);
  methods[26].selector = @selector(setState1WithId:);
  methods[27].selector = @selector(setState2WithId:);
  methods[28].selector = @selector(setState3WithId:);
  methods[29].selector = @selector(setState4WithId:);
  methods[30].selector = @selector(state0);
  methods[31].selector = @selector(state1);
  methods[32].selector = @selector(state2);
  methods[33].selector = @selector(state3);
  methods[34].selector = @selector(state4);
  methods[35].selector = @selector(stateYes);
  methods[36].selector = @selector(stateNo);
  methods[37].selector = @selector(endViewTransitionWithADView:);
  #pragma clang diagnostic pop
  static const J2ObjcFieldInfo fields[] = {
    { "this$0_", "LASCustomSwipeRefreshLayoutImpl;", .constantValue.asLong = 0, 0x1012, -1, -1, -1, -1 },
    { "measureFinished_", "LASMeasureEvent;", .constantValue.asLong = 0, 0x2, -1, -1, -1, -1 },
    { "onLayoutEvent_", "LASOnLayoutEvent;", .constantValue.asLong = 0, 0x2, -1, -1, -1, -1 },
    { "overlays_", "LJavaUtilList;", .constantValue.asLong = 0, 0x2, -1, -1, 37, -1 },
    { "mMaxWidth_", "I", .constantValue.asLong = 0, 0x2, -1, -1, -1, -1 },
    { "mMaxHeight_", "I", .constantValue.asLong = 0, 0x2, -1, -1, -1, -1 },
    { "templates_", "LJavaUtilMap;", .constantValue.asLong = 0, 0x2, -1, -1, 38, -1 },
  };
  static const void *ptrTable[] = { "setMaxWidth", "I", "setMaxHeight", "LASCustomSwipeRefreshLayoutImpl;", "onMeasure", "II", "onLayout", "ZIIII", "execute", "LNSString;[LNSObject;", "updateMeasuredDimension", "newInstance", "LASIWidget;", "setAttribute", "LASWidgetAttribute;LNSString;LNSObject;", "()Ljava/util/List<Ljava/lang/String;>;", "getAttribute", "LASWidgetAttribute;", "inflateView", "LNSString;", "getLocationOnScreen", "[I", "getWindowVisibleDisplayFrame", "LADRect;", "offsetTopAndBottom", "offsetLeftAndRight", "setMyAttribute", "LNSString;LNSObject;", "setVisibility", "setState0", "LNSObject;", "setState1", "setState2", "setState3", "setState4", "endViewTransition", "LADView;", "Ljava/util/List<Lcom/ashera/widget/IWidget;>;", "Ljava/util/Map<Ljava/lang/String;Lcom/ashera/widget/IWidget;>;" };
  static const J2ObjcClassInfo _ASCustomSwipeRefreshLayoutImpl_CustomSwipeRefreshLayoutExt = { "CustomSwipeRefreshLayoutExt", "com.ashera.swiperefreshlayout", ptrTable, methods, fields, 7, 0x1, 38, 7, 3, -1, -1, -1, -1 };
  return &_ASCustomSwipeRefreshLayoutImpl_CustomSwipeRefreshLayoutExt;
}

@end

void ASCustomSwipeRefreshLayoutImpl_CustomSwipeRefreshLayoutExt_initWithASCustomSwipeRefreshLayoutImpl_(ASCustomSwipeRefreshLayoutImpl_CustomSwipeRefreshLayoutExt *self, ASCustomSwipeRefreshLayoutImpl *outer$) {
  self->this$0_ = outer$;
  ASCustomSwipeRefreshLayout_init(self);
  self->measureFinished_ = new_ASMeasureEvent_init();
  self->onLayoutEvent_ = new_ASOnLayoutEvent_init();
  self->mMaxWidth_ = -1;
  self->mMaxHeight_ = -1;
}

ASCustomSwipeRefreshLayoutImpl_CustomSwipeRefreshLayoutExt *new_ASCustomSwipeRefreshLayoutImpl_CustomSwipeRefreshLayoutExt_initWithASCustomSwipeRefreshLayoutImpl_(ASCustomSwipeRefreshLayoutImpl *outer$) {
  J2OBJC_NEW_IMPL(ASCustomSwipeRefreshLayoutImpl_CustomSwipeRefreshLayoutExt, initWithASCustomSwipeRefreshLayoutImpl_, outer$)
}

ASCustomSwipeRefreshLayoutImpl_CustomSwipeRefreshLayoutExt *create_ASCustomSwipeRefreshLayoutImpl_CustomSwipeRefreshLayoutExt_initWithASCustomSwipeRefreshLayoutImpl_(ASCustomSwipeRefreshLayoutImpl *outer$) {
  J2OBJC_CREATE_IMPL(ASCustomSwipeRefreshLayoutImpl_CustomSwipeRefreshLayoutExt, initWithASCustomSwipeRefreshLayoutImpl_, outer$)
}

J2OBJC_CLASS_TYPE_LITERAL_SOURCE(ASCustomSwipeRefreshLayoutImpl_CustomSwipeRefreshLayoutExt)

@implementation ASCustomSwipeRefreshLayoutImpl_OnRefreshListener

- (NSString *)getAction {
  return action_;
}

- (instancetype)initWithASIWidget:(id<ASIWidget>)w
                     withNSString:(NSString *)strValue {
  ASCustomSwipeRefreshLayoutImpl_OnRefreshListener_initWithASIWidget_withNSString_(self, w, strValue);
  return self;
}

- (instancetype)initWithASIWidget:(id<ASIWidget>)w
                     withNSString:(NSString *)strValue
                     withNSString:(NSString *)action {
  ASCustomSwipeRefreshLayoutImpl_OnRefreshListener_initWithASIWidget_withNSString_withNSString_(self, w, strValue, action);
  return self;
}

- (void)onRefresh {
  if (action_ == nil || [action_ isEqual:@"onRefresh"]) {
    [((id<ASIWidget>) nil_chk(w_)) syncModelFromUiToPojoWithNSString:@"onRefresh"];
    id<JavaUtilMap> obj = [self getOnRefreshEventObj];
    NSString *commandName = (NSString *) cast_chk([((id<JavaUtilMap>) nil_chk(obj)) getWithId:ASEventExpressionParser_KEY_COMMAND_NAME], [NSString class]);
    NSString *commandType = (NSString *) cast_chk([obj getWithId:ASEventExpressionParser_KEY_COMMAND_TYPE], [NSString class]);
    switch (JreIndexOfStr(commandType, (id[]){ @"+" }, 1)) {
      case 0:
      if (ASEventCommandFactory_hasCommandWithNSString_(commandName)) {
        (void) [((id<ASEventCommand>) nil_chk(ASEventCommandFactory_getCommandWithNSString_(commandName))) executeCommandWithASIWidget:w_ withJavaUtilMap:obj withNSObjectArray:[IOSObjectArray newArrayWithLength:0 type:NSObject_class_()]];
      }
      break;
      default:
      break;
    }
    if ([obj containsKeyWithId:@"refreshUiFromModel"]) {
      id widgets = [obj removeWithId:@"refreshUiFromModel"];
      ASViewImpl_refreshUiFromModelWithASIWidget_withId_withBoolean_(w_, widgets, true);
    }
    if ([((id<ASIWidget>) nil_chk(w_)) getModelUiToPojoEventIds] != nil) {
      ASViewImpl_refreshUiFromModelWithASIWidget_withId_withBoolean_(w_, [((id<ASIWidget>) nil_chk(w_)) getModelUiToPojoEventIds], true);
    }
    if (strValue_ != nil && ![strValue_ isEmpty] && ![((NSString *) nil_chk([((NSString *) nil_chk(strValue_)) java_trim])) java_hasPrefix:@"+"]) {
      id<ASIActivity> activity = [((id<ASIFragment>) nil_chk([((id<ASIWidget>) nil_chk(w_)) getFragment])) getRootActivity];
      if (activity != nil) {
        [activity sendEventMessageWithJavaUtilMap:obj];
      }
    }
  }
  return;
}

- (id<JavaUtilMap>)getOnRefreshEventObj {
  id<JavaUtilMap> obj = ASPluginInvoker_getJSONCompatMap();
  (void) [((id<JavaUtilMap>) nil_chk(obj)) putWithId:@"action" withId:@"action"];
  (void) [obj putWithId:@"eventType" withId:@"refresh"];
  (void) [obj putWithId:@"fragmentId" withId:[((id<ASIFragment>) nil_chk([((id<ASIWidget>) nil_chk(w_)) getFragment])) getFragmentId]];
  (void) [obj putWithId:@"actionUrl" withId:[((id<ASIFragment>) nil_chk([((id<ASIWidget>) nil_chk(w_)) getFragment])) getActionUrl]];
  (void) [obj putWithId:@"namespace" withId:[((id<ASIFragment>) nil_chk([((id<ASIWidget>) nil_chk(w_)) getFragment])) getNamespace]];
  if ([((id<ASIWidget>) nil_chk(w_)) getComponentId] != nil) {
    (void) [obj putWithId:@"componentId" withId:[((id<ASIWidget>) nil_chk(w_)) getComponentId]];
  }
  ASPluginInvoker_putJSONSafeObjectIntoMapWithJavaUtilMap_withNSString_withId_(obj, @"id", [((id<ASIWidget>) nil_chk(w_)) getId]);
  (void) ASEventExpressionParser_parseEventExpressionWithNSString_withJavaUtilMap_(strValue_, obj);
  [((id<ASIWidget>) nil_chk(w_)) updateModelToEventMapWithJavaUtilMap:obj withNSString:@"onRefresh" withNSString:(NSString *) cast_chk([obj getWithId:ASEventExpressionParser_KEY_EVENT_ARGS], [NSString class])];
  return obj;
}

+ (const J2ObjcClassInfo *)__metadata {
  static J2ObjcMethodInfo methods[] = {
    { NULL, "LNSString;", 0x1, -1, -1, -1, -1, -1, -1 },
    { NULL, NULL, 0x1, -1, 0, -1, -1, -1, -1 },
    { NULL, NULL, 0x1, -1, 1, -1, -1, -1, -1 },
    { NULL, "V", 0x1, -1, -1, -1, -1, -1, -1 },
    { NULL, "LJavaUtilMap;", 0x1, -1, -1, -1, 2, -1, -1 },
  };
  #pragma clang diagnostic push
  #pragma clang diagnostic ignored "-Wobjc-multiple-method-names"
  #pragma clang diagnostic ignored "-Wundeclared-selector"
  methods[0].selector = @selector(getAction);
  methods[1].selector = @selector(initWithASIWidget:withNSString:);
  methods[2].selector = @selector(initWithASIWidget:withNSString:withNSString:);
  methods[3].selector = @selector(onRefresh);
  methods[4].selector = @selector(getOnRefreshEventObj);
  #pragma clang diagnostic pop
  static const J2ObjcFieldInfo fields[] = {
    { "w_", "LASIWidget;", .constantValue.asLong = 0, 0x2, -1, -1, -1, -1 },
    { "view_", "LADView;", .constantValue.asLong = 0, 0x2, -1, -1, -1, -1 },
    { "strValue_", "LNSString;", .constantValue.asLong = 0, 0x2, -1, -1, -1, -1 },
    { "action_", "LNSString;", .constantValue.asLong = 0, 0x2, -1, -1, -1, -1 },
  };
  static const void *ptrTable[] = { "LASIWidget;LNSString;", "LASIWidget;LNSString;LNSString;", "()Ljava/util/Map<Ljava/lang/String;Ljava/lang/Object;>;", "LASCustomSwipeRefreshLayoutImpl;" };
  static const J2ObjcClassInfo _ASCustomSwipeRefreshLayoutImpl_OnRefreshListener = { "OnRefreshListener", "com.ashera.swiperefreshlayout", ptrTable, methods, fields, 7, 0xa, 5, 4, 3, -1, -1, -1, -1 };
  return &_ASCustomSwipeRefreshLayoutImpl_OnRefreshListener;
}

@end

void ASCustomSwipeRefreshLayoutImpl_OnRefreshListener_initWithASIWidget_withNSString_(ASCustomSwipeRefreshLayoutImpl_OnRefreshListener *self, id<ASIWidget> w, NSString *strValue) {
  NSObject_init(self);
  self->w_ = w;
  self->strValue_ = strValue;
}

ASCustomSwipeRefreshLayoutImpl_OnRefreshListener *new_ASCustomSwipeRefreshLayoutImpl_OnRefreshListener_initWithASIWidget_withNSString_(id<ASIWidget> w, NSString *strValue) {
  J2OBJC_NEW_IMPL(ASCustomSwipeRefreshLayoutImpl_OnRefreshListener, initWithASIWidget_withNSString_, w, strValue)
}

ASCustomSwipeRefreshLayoutImpl_OnRefreshListener *create_ASCustomSwipeRefreshLayoutImpl_OnRefreshListener_initWithASIWidget_withNSString_(id<ASIWidget> w, NSString *strValue) {
  J2OBJC_CREATE_IMPL(ASCustomSwipeRefreshLayoutImpl_OnRefreshListener, initWithASIWidget_withNSString_, w, strValue)
}

void ASCustomSwipeRefreshLayoutImpl_OnRefreshListener_initWithASIWidget_withNSString_withNSString_(ASCustomSwipeRefreshLayoutImpl_OnRefreshListener *self, id<ASIWidget> w, NSString *strValue, NSString *action) {
  NSObject_init(self);
  self->w_ = w;
  self->strValue_ = strValue;
  self->action_ = action;
}

ASCustomSwipeRefreshLayoutImpl_OnRefreshListener *new_ASCustomSwipeRefreshLayoutImpl_OnRefreshListener_initWithASIWidget_withNSString_withNSString_(id<ASIWidget> w, NSString *strValue, NSString *action) {
  J2OBJC_NEW_IMPL(ASCustomSwipeRefreshLayoutImpl_OnRefreshListener, initWithASIWidget_withNSString_withNSString_, w, strValue, action)
}

ASCustomSwipeRefreshLayoutImpl_OnRefreshListener *create_ASCustomSwipeRefreshLayoutImpl_OnRefreshListener_initWithASIWidget_withNSString_withNSString_(id<ASIWidget> w, NSString *strValue, NSString *action) {
  J2OBJC_CREATE_IMPL(ASCustomSwipeRefreshLayoutImpl_OnRefreshListener, initWithASIWidget_withNSString_withNSString_, w, strValue, action)
}

J2OBJC_CLASS_TYPE_LITERAL_SOURCE(ASCustomSwipeRefreshLayoutImpl_OnRefreshListener)

@implementation ASCustomSwipeRefreshLayoutImpl_1

- (instancetype)initWithASCustomSwipeRefreshLayoutImpl:(ASCustomSwipeRefreshLayoutImpl *)outer$ {
  ASCustomSwipeRefreshLayoutImpl_1_initWithASCustomSwipeRefreshLayoutImpl_(self, outer$);
  return self;
}

- (void)handlePanStartWithASIWidget:(id<ASIWidget>)widget
                             withId:(id)eventWidget
                            withInt:(int32_t)x
                            withInt:(int32_t)y {
  this$0_->action_ = 1;
  ASCustomSwipeRefreshLayoutImpl_processTouchEventWithInt_withInt_withInt_(this$0_, ADMotionEvent_ACTION_DOWN, x, y);
}

- (void)handlePanDragWithASIWidget:(id<ASIWidget>)widget
                            withId:(id)eventWidget
                           withInt:(int32_t)x
                           withInt:(int32_t)y {
  if (this$0_->action_ == 1) {
    if (ASCustomSwipeRefreshLayoutImpl_processTouchEventWithInt_withInt_withInt_(this$0_, ADMotionEvent_ACTION_MOVE, x, y)) {
      [((ASEventBus *) nil_chk([((id<ASIFragment>) nil_chk(this$0_->fragment_)) getEventBus])) notifyObserversWithNSString:@"scrollEnabled" withId:JreLoadStatic(JavaLangBoolean, FALSE)];
    }
  }
}

- (void)handlePanEndWithASIWidget:(id<ASIWidget>)widget
                           withId:(id)eventWidget
                          withInt:(int32_t)x
                          withInt:(int32_t)y {
  if (this$0_->action_ == 1) {
    ASCustomSwipeRefreshLayoutImpl_processTouchEventWithInt_withInt_withInt_(this$0_, ADMotionEvent_ACTION_UP, x, y);
    this$0_->action_ = 0;
    [((ASEventBus *) nil_chk([((id<ASIFragment>) nil_chk(this$0_->fragment_)) getEventBus])) notifyObserversWithNSString:@"scrollEnabled" withId:JreLoadStatic(JavaLangBoolean, TRUE)];
  }
}

+ (const J2ObjcClassInfo *)__metadata {
  static J2ObjcMethodInfo methods[] = {
    { NULL, NULL, 0x0, -1, 0, -1, -1, -1, -1 },
    { NULL, "V", 0x1, 1, 2, -1, -1, -1, -1 },
    { NULL, "V", 0x1, 3, 2, -1, -1, -1, -1 },
    { NULL, "V", 0x1, 4, 2, -1, -1, -1, -1 },
  };
  #pragma clang diagnostic push
  #pragma clang diagnostic ignored "-Wobjc-multiple-method-names"
  #pragma clang diagnostic ignored "-Wundeclared-selector"
  methods[0].selector = @selector(initWithASCustomSwipeRefreshLayoutImpl:);
  methods[1].selector = @selector(handlePanStartWithASIWidget:withId:withInt:withInt:);
  methods[2].selector = @selector(handlePanDragWithASIWidget:withId:withInt:withInt:);
  methods[3].selector = @selector(handlePanEndWithASIWidget:withId:withInt:withInt:);
  #pragma clang diagnostic pop
  static const J2ObjcFieldInfo fields[] = {
    { "this$0_", "LASCustomSwipeRefreshLayoutImpl;", .constantValue.asLong = 0, 0x1012, -1, -1, -1, -1 },
  };
  static const void *ptrTable[] = { "LASCustomSwipeRefreshLayoutImpl;", "handlePanStart", "LASIWidget;LNSObject;II", "handlePanDrag", "handlePanEnd", "initialized" };
  static const J2ObjcClassInfo _ASCustomSwipeRefreshLayoutImpl_1 = { "", "com.ashera.swiperefreshlayout", ptrTable, methods, fields, 7, 0x8000, 4, 1, 0, -1, 5, -1, -1 };
  return &_ASCustomSwipeRefreshLayoutImpl_1;
}

@end

void ASCustomSwipeRefreshLayoutImpl_1_initWithASCustomSwipeRefreshLayoutImpl_(ASCustomSwipeRefreshLayoutImpl_1 *self, ASCustomSwipeRefreshLayoutImpl *outer$) {
  self->this$0_ = outer$;
  NSObject_init(self);
}

ASCustomSwipeRefreshLayoutImpl_1 *new_ASCustomSwipeRefreshLayoutImpl_1_initWithASCustomSwipeRefreshLayoutImpl_(ASCustomSwipeRefreshLayoutImpl *outer$) {
  J2OBJC_NEW_IMPL(ASCustomSwipeRefreshLayoutImpl_1, initWithASCustomSwipeRefreshLayoutImpl_, outer$)
}

ASCustomSwipeRefreshLayoutImpl_1 *create_ASCustomSwipeRefreshLayoutImpl_1_initWithASCustomSwipeRefreshLayoutImpl_(ASCustomSwipeRefreshLayoutImpl *outer$) {
  J2OBJC_CREATE_IMPL(ASCustomSwipeRefreshLayoutImpl_1, initWithASCustomSwipeRefreshLayoutImpl_, outer$)
}

@implementation ASCustomSwipeRefreshLayoutImpl_$Lambda$1

- (void)run {
  ASViewGroupImpl_nativeRemoveViewWithASIWidget_(val$widget_);
}

@end

void ASCustomSwipeRefreshLayoutImpl_$Lambda$1_initWithASIWidget_(ASCustomSwipeRefreshLayoutImpl_$Lambda$1 *self, id<ASIWidget> capture$0) {
  self->val$widget_ = capture$0;
  NSObject_init(self);
}

ASCustomSwipeRefreshLayoutImpl_$Lambda$1 *new_ASCustomSwipeRefreshLayoutImpl_$Lambda$1_initWithASIWidget_(id<ASIWidget> capture$0) {
  J2OBJC_NEW_IMPL(ASCustomSwipeRefreshLayoutImpl_$Lambda$1, initWithASIWidget_, capture$0)
}

ASCustomSwipeRefreshLayoutImpl_$Lambda$1 *create_ASCustomSwipeRefreshLayoutImpl_$Lambda$1_initWithASIWidget_(id<ASIWidget> capture$0) {
  J2OBJC_CREATE_IMPL(ASCustomSwipeRefreshLayoutImpl_$Lambda$1, initWithASIWidget_, capture$0)
}
