//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: D:\Java\git\core-ios-widgets\IOSSwipeRefreshLayoutPlugin\src\main\java\com\reginald\swiperefresh\CustomSwipeProgressBar.java
//

#define J2OBJC_IMPORTED_BY_JAVA_IMPLEMENTATION 1




#include "CustomSwipeProgressBar.h"
#include "IWidget.h"
#include "J2ObjC_source.h"
#include "View.h"
#include "ViewGroupImpl.h"
#include "ViewImpl.h"
#include "java/lang/Float.h"
#include "java/lang/Integer.h"

#include <UIKit/UIKit.h>
#include "LineSwipeProgressBar.h"




#pragma clang diagnostic error "-Wreturn-type"
#pragma clang diagnostic ignored "-Wswitch"


@interface ASCustomSwipeProgressBar () {
 @public
  id lineSwipeProgressBar_;
  ADView *parent_;
}

- (void)init__ OBJC_METHOD_FAMILY_NONE;

@end

J2OBJC_FIELD_SETTER(ASCustomSwipeProgressBar, lineSwipeProgressBar_, id)
J2OBJC_FIELD_SETTER(ASCustomSwipeProgressBar, parent_, ADView *)

__attribute__((unused)) static void ASCustomSwipeProgressBar_init__(ASCustomSwipeProgressBar *self);

@implementation ASCustomSwipeProgressBar

@synthesize lineSwipeProgressBar = lineSwipeProgressBar_;

- (instancetype)initWithADView:(ADView *)parent {
  ASCustomSwipeProgressBar_initWithADView_(self, parent);
  return self;
}

- (void)nativeSetTriggerPercentageWithFloat:(float)f
                                     withId:(id)view {
  [(LineSwipeProgressBar*)view setTriggerPercentage: f];
}

- (void)setTriggerPercentageWithFloat:(float)f {
  [self nativeSetTriggerPercentageWithFloat:f withId:lineSwipeProgressBar_];
}

- (void)stop {
  if (lineSwipeProgressBar_ != nil) {
    [self nativeStopWithId:lineSwipeProgressBar_];
  }
}

- (void)nativeStopWithId:(id)view {
  [(LineSwipeProgressBar*)view stop];
}

- (void)start {
  ASCustomSwipeProgressBar_init__(self);
  [self nativeStartWithId:lineSwipeProgressBar_];
}

- (void)nativeStartWithId:(id)view {
  [(LineSwipeProgressBar*)view start];
}

- (void)setBoundsWithInt:(int32_t)left
                 withInt:(int32_t)top
                 withInt:(int32_t)right
                 withInt:(int32_t)bottom {
  ASCustomSwipeProgressBar_init__(self);
  ASViewImpl_nativeMakeFrameWithId_withInt_withInt_withInt_withInt_(lineSwipeProgressBar_, left, top, right, bottom);
}

- (void)init__ {
  ASCustomSwipeProgressBar_init__(self);
}

- (void)nativeCreate {
  LineSwipeProgressBar* uiView = [LineSwipeProgressBar new];
  lineSwipeProgressBar_ = uiView;
}

- (void)setProgressBarColorWithId:(id)color1
                           withId:(id)color2
                           withId:(id)color3
                           withId:(id)color4 {
  ASCustomSwipeProgressBar_init__(self);
  [self nativesetProgressBarColorWithId:color1 withId:color2 withId:color3 withId:color4 withId:lineSwipeProgressBar_];
}

- (void)nativesetProgressBarColorWithId:(id)c1
                                 withId:(id)c2
                                 withId:(id)c3
                                 withId:(id)c4
                                 withId:(id)view {
  [(LineSwipeProgressBar*)view setColorScheme: (UIColor*) c1 :(UIColor*)c2 :(UIColor*)c3 :(UIColor*)c4];
}

+ (const J2ObjcClassInfo *)__metadata {
  static J2ObjcMethodInfo methods[] = {
    { NULL, NULL, 0x1, -1, 0, -1, -1, -1, -1 },
    { NULL, "V", 0x101, 1, 2, -1, -1, -1, -1 },
    { NULL, "V", 0x1, 3, 4, -1, -1, -1, -1 },
    { NULL, "V", 0x1, -1, -1, -1, -1, -1, -1 },
    { NULL, "V", 0x101, 5, 6, -1, -1, -1, -1 },
    { NULL, "V", 0x1, -1, -1, -1, -1, -1, -1 },
    { NULL, "V", 0x101, 7, 6, -1, -1, -1, -1 },
    { NULL, "V", 0x1, 8, 9, -1, -1, -1, -1 },
    { NULL, "V", 0x2, 10, -1, -1, -1, -1, -1 },
    { NULL, "V", 0x101, -1, -1, -1, -1, -1, -1 },
    { NULL, "V", 0x1, 11, 12, -1, -1, -1, -1 },
    { NULL, "V", 0x101, 13, 14, -1, -1, -1, -1 },
  };
  #pragma clang diagnostic push
  #pragma clang diagnostic ignored "-Wobjc-multiple-method-names"
  #pragma clang diagnostic ignored "-Wundeclared-selector"
  methods[0].selector = @selector(initWithADView:);
  methods[1].selector = @selector(nativeSetTriggerPercentageWithFloat:withId:);
  methods[2].selector = @selector(setTriggerPercentageWithFloat:);
  methods[3].selector = @selector(stop);
  methods[4].selector = @selector(nativeStopWithId:);
  methods[5].selector = @selector(start);
  methods[6].selector = @selector(nativeStartWithId:);
  methods[7].selector = @selector(setBoundsWithInt:withInt:withInt:withInt:);
  methods[8].selector = @selector(init__);
  methods[9].selector = @selector(nativeCreate);
  methods[10].selector = @selector(setProgressBarColorWithId:withId:withId:withId:);
  methods[11].selector = @selector(nativesetProgressBarColorWithId:withId:withId:withId:withId:);
  #pragma clang diagnostic pop
  static const J2ObjcFieldInfo fields[] = {
    { "lineSwipeProgressBar_", "LNSObject;", .constantValue.asLong = 0, 0x2, -1, -1, -1, -1 },
    { "parent_", "LADView;", .constantValue.asLong = 0, 0x2, -1, -1, -1, -1 },
  };
  static const void *ptrTable[] = { "LADView;", "nativeSetTriggerPercentage", "FLNSObject;", "setTriggerPercentage", "F", "nativeStop", "LNSObject;", "nativeStart", "setBounds", "IIII", "init", "setProgressBarColor", "LNSObject;LNSObject;LNSObject;LNSObject;", "nativesetProgressBarColor", "LNSObject;LNSObject;LNSObject;LNSObject;LNSObject;" };
  static const J2ObjcClassInfo _ASCustomSwipeProgressBar = { "CustomSwipeProgressBar", "com.reginald.swiperefresh", ptrTable, methods, fields, 7, 0x1, 12, 2, -1, -1, -1, -1, -1 };
  return &_ASCustomSwipeProgressBar;
}

@end

void ASCustomSwipeProgressBar_initWithADView_(ASCustomSwipeProgressBar *self, ADView *parent) {
  NSObject_init(self);
  self->parent_ = parent;
}

ASCustomSwipeProgressBar *new_ASCustomSwipeProgressBar_initWithADView_(ADView *parent) {
  J2OBJC_NEW_IMPL(ASCustomSwipeProgressBar, initWithADView_, parent)
}

ASCustomSwipeProgressBar *create_ASCustomSwipeProgressBar_initWithADView_(ADView *parent) {
  J2OBJC_CREATE_IMPL(ASCustomSwipeProgressBar, initWithADView_, parent)
}

void ASCustomSwipeProgressBar_init__(ASCustomSwipeProgressBar *self) {
  if (self->lineSwipeProgressBar_ == nil) {
    [self nativeCreate];
    ASViewGroupImpl_nativeAddViewWithId_withId_([((id<ASIWidget>) nil_chk([((ADView *) nil_chk(self->parent_)) getOuterWidget])) asNativeWidget], self->lineSwipeProgressBar_);
  }
}

J2OBJC_CLASS_TYPE_LITERAL_SOURCE(ASCustomSwipeProgressBar)

J2OBJC_NAME_MAPPING(ASCustomSwipeProgressBar, "com.reginald.swiperefresh", "AS")
