//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: D:\Java\git\core-ios-widgets\IOSSwipeRefreshLayoutPlugin\src\main\java\com\reginald\swiperefresh\DefaultCustomHeadView.java
//

#import <Foundation/Foundation.h>
#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_DefaultCustomHeadView")
#ifdef RESTRICT_DefaultCustomHeadView
#define INCLUDE_ALL_DefaultCustomHeadView 0
#else
#define INCLUDE_ALL_DefaultCustomHeadView 1
#endif
#undef RESTRICT_DefaultCustomHeadView

#if !defined (ASDefaultCustomHeadView_) && (INCLUDE_ALL_DefaultCustomHeadView || defined(INCLUDE_ASDefaultCustomHeadView))
#define ASDefaultCustomHeadView_

#define RESTRICT_LinearLayout 1
#define INCLUDE_ADLinearLayout 1
#include "LinearLayout.h"

#define RESTRICT_CustomSwipeRefreshLayout 1
#define INCLUDE_ASCustomSwipeRefreshLayout_CustomSwipeRefreshHeadLayout 1
#include "CustomSwipeRefreshLayout.h"

@class ADContext;
@class ASCustomSwipeRefreshLayout_State;
@class NSString;

/*!
 @brief The DefaultCustomHeadViewLayout is a refresh head view provided as default.
 You can also make your own head view layout which must implement
  CustomSwipeRefreshHeadview.CustomSwipeRefreshHeadLayout interface.
 */
@interface ASDefaultCustomHeadView : ADLinearLayout < ASCustomSwipeRefreshLayout_CustomSwipeRefreshHeadLayout >

#pragma mark Public

- (instancetype)init;

- (instancetype)initWithADContext:(ADContext *)context;

- (NSString *)fetchData;

- (void)onStateChangeWithASCustomSwipeRefreshLayout_State:(ASCustomSwipeRefreshLayout_State *)state
                     withASCustomSwipeRefreshLayout_State:(ASCustomSwipeRefreshLayout_State *)lastState;

- (void)setupAnimation;

- (void)setupLayoutWithNSString:(NSString *)layout;

- (void)updateData;

@end

J2OBJC_EMPTY_STATIC_INIT(ASDefaultCustomHeadView)

FOUNDATION_EXPORT void ASDefaultCustomHeadView_init(ASDefaultCustomHeadView *self);

FOUNDATION_EXPORT ASDefaultCustomHeadView *new_ASDefaultCustomHeadView_init(void) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT ASDefaultCustomHeadView *create_ASDefaultCustomHeadView_init(void);

FOUNDATION_EXPORT void ASDefaultCustomHeadView_initWithADContext_(ASDefaultCustomHeadView *self, ADContext *context);

FOUNDATION_EXPORT ASDefaultCustomHeadView *new_ASDefaultCustomHeadView_initWithADContext_(ADContext *context) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT ASDefaultCustomHeadView *create_ASDefaultCustomHeadView_initWithADContext_(ADContext *context);

J2OBJC_TYPE_LITERAL_HEADER(ASDefaultCustomHeadView)

@compatibility_alias ComReginaldSwiperefreshDefaultCustomHeadView ASDefaultCustomHeadView;


#endif

#pragma pop_macro("INCLUDE_ALL_DefaultCustomHeadView")
