//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: D:\Java\git\core-ios-widgets\IOSSwipeRefreshLayoutPlugin\src\main\java\com\reginald\swiperefresh\DefaultCustomHeadView.java
//

#define J2OBJC_IMPORTED_BY_JAVA_IMPLEMENTATION 1




#include "Animation.h"
#include "Context.h"
#include "CustomSwipeRefreshLayout.h"
#include "DefaultCustomHeadView.h"
#include "Gravity.h"
#include "IConverter.h"
#include "IFragment.h"
#include "IWidget.h"
#include "ImageView.h"
#include "J2ObjC_source.h"
#include "LayoutInflater.h"
#include "LinearLayout.h"
#include "PluginInvoker.h"
#include "ProgressBar.h"
#include "RotateAnimation.h"
#include "TextView.h"
#include "View.h"
#include "ViewGroup.h"
#include "java/lang/Boolean.h"
#include "java/lang/Character.h"
#include "java/lang/Float.h"
#include "java/lang/Integer.h"
#include "java/text/SimpleDateFormat.h"
#include "java/util/Date.h"




#pragma clang diagnostic error "-Wreturn-type"
#pragma clang diagnostic ignored "-Wswitch"


@interface ASDefaultCustomHeadView () {
 @public
  ADLinearLayout *mContainer_;
  ADTextView *mMainTextView_;
  ADTextView *mSubTextView_;
  ADImageView *mImageView_;
  ADProgressBar *mProgressBar_;
  ADAnimation *mRotateUpAnim_;
  ADAnimation *mRotateDownAnim_;
  id<ADAnimation_AnimationListener> animationListener_;
}

@end

J2OBJC_FIELD_SETTER(ASDefaultCustomHeadView, mContainer_, ADLinearLayout *)
J2OBJC_FIELD_SETTER(ASDefaultCustomHeadView, mMainTextView_, ADTextView *)
J2OBJC_FIELD_SETTER(ASDefaultCustomHeadView, mSubTextView_, ADTextView *)
J2OBJC_FIELD_SETTER(ASDefaultCustomHeadView, mImageView_, ADImageView *)
J2OBJC_FIELD_SETTER(ASDefaultCustomHeadView, mProgressBar_, ADProgressBar *)
J2OBJC_FIELD_SETTER(ASDefaultCustomHeadView, mRotateUpAnim_, ADAnimation *)
J2OBJC_FIELD_SETTER(ASDefaultCustomHeadView, mRotateDownAnim_, ADAnimation *)
J2OBJC_FIELD_SETTER(ASDefaultCustomHeadView, animationListener_, id<ADAnimation_AnimationListener>)

inline int32_t ASDefaultCustomHeadView_get_ROTATE_ANIM_DURATION(void);
#define ASDefaultCustomHeadView_ROTATE_ANIM_DURATION 180
J2OBJC_STATIC_FIELD_CONSTANT(ASDefaultCustomHeadView, ROTATE_ANIM_DURATION, int32_t)

@implementation ASDefaultCustomHeadView

J2OBJC_IGNORE_DESIGNATED_BEGIN
- (instancetype)init {
  ASDefaultCustomHeadView_init(self);
  return self;
}
J2OBJC_IGNORE_DESIGNATED_END

- (instancetype)initWithADContext:(ADContext *)context {
  ASDefaultCustomHeadView_initWithADContext_(self, context);
  return self;
}

- (void)setupLayoutWithNSString:(NSString *)layout {
  if (layout == nil) {
    layout = @"@layout/default_swiperefresh_head_layout";
  }
  ADLinearLayout_LayoutParams *lp = new_ADLinearLayout_LayoutParams_initWithInt_withInt_(ADViewGroup_LayoutParams_MATCH_PARENT, ADViewGroup_LayoutParams_MATCH_PARENT);
  mContainer_ = (ADLinearLayout *) cast_chk([((ADLayoutInflater *) nil_chk(ADLayoutInflater_fromWithADContext_([self getContext]))) inflateWithNSString:layout withADViewGroup:self withBoolean:false], [ADLinearLayout class]);
  [self addViewWithADView:mContainer_ withADViewGroup_LayoutParams:lp];
  [self setGravityWithInt:ADGravity_BOTTOM];
  mImageView_ = (ADImageView *) cast_chk([((id<ASIWidget>) nil_chk([((id<ASIWidget>) nil_chk([((ADLinearLayout *) nil_chk(mContainer_)) getOuterWidget])) findWidgetByIdWithNSString:@"@+id/default_header_arrow"])) asWidget], [ADImageView class]);
  mMainTextView_ = (ADTextView *) cast_chk([((id<ASIWidget>) nil_chk([((id<ASIWidget>) nil_chk([((ADLinearLayout *) nil_chk(mContainer_)) getOuterWidget])) findWidgetByIdWithNSString:@"@+id/default_header_textview"])) asWidget], [ADTextView class]);
  mSubTextView_ = (ADTextView *) cast_chk([((id<ASIWidget>) nil_chk([((id<ASIWidget>) nil_chk([((ADLinearLayout *) nil_chk(mContainer_)) getOuterWidget])) findWidgetByIdWithNSString:@"@+id/default_header_time"])) asWidget], [ADTextView class]);
  mProgressBar_ = (ADProgressBar *) cast_chk([((id<ASIWidget>) nil_chk([((id<ASIWidget>) nil_chk([((ADLinearLayout *) nil_chk(mContainer_)) getOuterWidget])) findWidgetByIdWithNSString:@"@+id/default_header_progressbar"])) asWidget], [ADProgressBar class]);
  [self setupAnimation];
}

- (void)setupAnimation {
  mRotateUpAnim_ = new_ADRotateAnimation_initWithFloat_withFloat_withInt_withFloat_withInt_withFloat_(0.0f, -180.0f, ADAnimation_RELATIVE_TO_SELF, 0.5f, ADAnimation_RELATIVE_TO_SELF, 0.5f);
  id<ADAnimation_AnimationListener> mRotateUpAnimListener = animationListener_;
  [mRotateUpAnim_ setAnimationListenerWithADAnimation_AnimationListener:mRotateUpAnimListener];
  [((ADAnimation *) nil_chk(mRotateUpAnim_)) setDurationWithInt:ASDefaultCustomHeadView_ROTATE_ANIM_DURATION];
  [((ADAnimation *) nil_chk(mRotateUpAnim_)) setFillAfterWithBoolean:true];
  mRotateDownAnim_ = new_ADRotateAnimation_initWithFloat_withFloat_withInt_withFloat_withInt_withFloat_(-180.0f, 0.0f, ADAnimation_RELATIVE_TO_SELF, 0.5f, ADAnimation_RELATIVE_TO_SELF, 0.5f);
  [mRotateDownAnim_ setDurationWithInt:ASDefaultCustomHeadView_ROTATE_ANIM_DURATION];
  [((ADAnimation *) nil_chk(mRotateDownAnim_)) setFillAfterWithBoolean:true];
}

- (void)onStateChangeWithASCustomSwipeRefreshLayout_State:(ASCustomSwipeRefreshLayout_State *)state
                     withASCustomSwipeRefreshLayout_State:(ASCustomSwipeRefreshLayout_State *)lastState {
  int32_t stateCode = [((ASCustomSwipeRefreshLayout_State *) nil_chk(state)) getRefreshState];
  int32_t lastStateCode = [((ASCustomSwipeRefreshLayout_State *) nil_chk(lastState)) getRefreshState];
  if (stateCode == lastStateCode) {
    return;
  }
  if (stateCode == ASCustomSwipeRefreshLayout_State_STATE_COMPLETE) {
    [((ADImageView *) nil_chk(mImageView_)) clearAnimation];
    [((ADImageView *) nil_chk(mImageView_)) setVisibilityWithInt:ADView_INVISIBLE];
    [((ADProgressBar *) nil_chk(mProgressBar_)) setVisibilityWithInt:ADView_INVISIBLE];
  }
  else if (stateCode == ASCustomSwipeRefreshLayout_State_STATE_REFRESHING) {
    [((ADImageView *) nil_chk(mImageView_)) clearAnimation];
    [((ADImageView *) nil_chk(mImageView_)) setVisibilityWithInt:ADView_INVISIBLE];
    [((ADProgressBar *) nil_chk(mProgressBar_)) setVisibilityWithInt:ADView_VISIBLE];
  }
  else {
    [((ADImageView *) nil_chk(mImageView_)) setVisibilityWithInt:ADView_VISIBLE];
    [((ADProgressBar *) nil_chk(mProgressBar_)) setVisibilityWithInt:ADView_INVISIBLE];
  }
  switch (stateCode) {
    case ASCustomSwipeRefreshLayout_State_STATE_NORMAL:
    if (lastStateCode == ASCustomSwipeRefreshLayout_State_STATE_READY) {
      [((ADImageView *) nil_chk(mImageView_)) startAnimationWithADAnimation:mRotateDownAnim_];
    }
    if (lastStateCode == ASCustomSwipeRefreshLayout_State_STATE_REFRESHING) {
      [((ADImageView *) nil_chk(mImageView_)) clearAnimation];
    }
    [((ADTextView *) nil_chk(mMainTextView_)) setTextWithNSString:@"@string/csr_text_state_normal"];
    break;
    case ASCustomSwipeRefreshLayout_State_STATE_READY:
    if (lastStateCode != ASCustomSwipeRefreshLayout_State_STATE_READY) {
      [((ADImageView *) nil_chk(mImageView_)) clearAnimation];
      [((ADImageView *) nil_chk(mImageView_)) startAnimationWithADAnimation:mRotateUpAnim_];
      [((ADTextView *) nil_chk(mMainTextView_)) setTextWithNSString:@"@string/csr_text_state_ready"];
    }
    break;
    case ASCustomSwipeRefreshLayout_State_STATE_REFRESHING:
    [((ADTextView *) nil_chk(mMainTextView_)) setTextWithNSString:@"@string/csr_text_state_refresh"];
    [self updateData];
    break;
    case ASCustomSwipeRefreshLayout_State_STATE_COMPLETE:
    [((ADTextView *) nil_chk(mMainTextView_)) setTextWithNSString:@"@string/csr_text_state_complete"];
    [self updateData];
    break;
    default:
    ;
  }
  [((ADProgressBar *) nil_chk(mProgressBar_)) remeasure];
}

- (void)updateData {
  NSString *time = [self fetchData];
  if (time != nil) {
    [((ADTextView *) nil_chk(mSubTextView_)) setVisibilityWithInt:ADView_VISIBLE];
    [((ADTextView *) nil_chk(mSubTextView_)) setTextWithNSString:time];
  }
  else {
    [((ADTextView *) nil_chk(mSubTextView_)) setVisibilityWithInt:ADView_GONE];
  }
}

- (NSString *)fetchData {
  return JreStrcat("@C$", ([((id<ASIConverter>) nil_chk(ASPluginInvoker_getConverterWithNSString_(@"resourcestring"))) convertFromWithId:@"@string/csr_text_last_refresh" withJavaUtilMap:nil withASIFragment:[((id<ASIWidget>) nil_chk([self getOuterWidget])) getFragment]]), ' ', [new_JavaTextSimpleDateFormat_initWithNSString_(@"yyyy-MM-dd HH:mm:ss") formatWithJavaUtilDate:new_JavaUtilDate_init()]);
}

+ (const J2ObjcClassInfo *)__metadata {
  static J2ObjcMethodInfo methods[] = {
    { NULL, NULL, 0x1, -1, -1, -1, -1, -1, -1 },
    { NULL, NULL, 0x1, -1, 0, -1, -1, -1, -1 },
    { NULL, "V", 0x1, 1, 2, -1, -1, -1, -1 },
    { NULL, "V", 0x1, -1, -1, -1, -1, -1, -1 },
    { NULL, "V", 0x1, 3, 4, -1, -1, -1, -1 },
    { NULL, "V", 0x1, -1, -1, -1, -1, -1, -1 },
    { NULL, "LNSString;", 0x1, -1, -1, -1, -1, -1, -1 },
  };
  #pragma clang diagnostic push
  #pragma clang diagnostic ignored "-Wobjc-multiple-method-names"
  #pragma clang diagnostic ignored "-Wundeclared-selector"
  methods[0].selector = @selector(init);
  methods[1].selector = @selector(initWithADContext:);
  methods[2].selector = @selector(setupLayoutWithNSString:);
  methods[3].selector = @selector(setupAnimation);
  methods[4].selector = @selector(onStateChangeWithASCustomSwipeRefreshLayout_State:withASCustomSwipeRefreshLayout_State:);
  methods[5].selector = @selector(updateData);
  methods[6].selector = @selector(fetchData);
  #pragma clang diagnostic pop
  static const J2ObjcFieldInfo fields[] = {
    { "mContainer_", "LADLinearLayout;", .constantValue.asLong = 0, 0x2, -1, -1, -1, -1 },
    { "mMainTextView_", "LADTextView;", .constantValue.asLong = 0, 0x2, -1, -1, -1, -1 },
    { "mSubTextView_", "LADTextView;", .constantValue.asLong = 0, 0x2, -1, -1, -1, -1 },
    { "mImageView_", "LADImageView;", .constantValue.asLong = 0, 0x2, -1, -1, -1, -1 },
    { "mProgressBar_", "LADProgressBar;", .constantValue.asLong = 0, 0x2, -1, -1, -1, -1 },
    { "mRotateUpAnim_", "LADAnimation;", .constantValue.asLong = 0, 0x2, -1, -1, -1, -1 },
    { "mRotateDownAnim_", "LADAnimation;", .constantValue.asLong = 0, 0x2, -1, -1, -1, -1 },
    { "ROTATE_ANIM_DURATION", "I", .constantValue.asInt = ASDefaultCustomHeadView_ROTATE_ANIM_DURATION, 0x12, 5, -1, -1, -1 },
    { "animationListener_", "LADAnimation_AnimationListener;", .constantValue.asLong = 0, 0x2, -1, -1, -1, -1 },
  };
  static const void *ptrTable[] = { "LADContext;", "setupLayout", "LNSString;", "onStateChange", "LASCustomSwipeRefreshLayout_State;LASCustomSwipeRefreshLayout_State;", "ROTATE_ANIM_DURATION" };
  static const J2ObjcClassInfo _ASDefaultCustomHeadView = { "DefaultCustomHeadView", "com.reginald.swiperefresh", ptrTable, methods, fields, 7, 0x1, 7, 9, -1, -1, -1, -1, -1 };
  return &_ASDefaultCustomHeadView;
}

@end

void ASDefaultCustomHeadView_init(ASDefaultCustomHeadView *self) {
  ADLinearLayout_init(self);
  [self setWillNotDrawWithBoolean:false];
}

ASDefaultCustomHeadView *new_ASDefaultCustomHeadView_init() {
  J2OBJC_NEW_IMPL(ASDefaultCustomHeadView, init)
}

ASDefaultCustomHeadView *create_ASDefaultCustomHeadView_init() {
  J2OBJC_CREATE_IMPL(ASDefaultCustomHeadView, init)
}

void ASDefaultCustomHeadView_initWithADContext_(ASDefaultCustomHeadView *self, ADContext *context) {
  ADLinearLayout_initWithADContext_(self, context);
  [self setWillNotDrawWithBoolean:false];
  [self setupLayoutWithNSString:nil];
}

ASDefaultCustomHeadView *new_ASDefaultCustomHeadView_initWithADContext_(ADContext *context) {
  J2OBJC_NEW_IMPL(ASDefaultCustomHeadView, initWithADContext_, context)
}

ASDefaultCustomHeadView *create_ASDefaultCustomHeadView_initWithADContext_(ADContext *context) {
  J2OBJC_CREATE_IMPL(ASDefaultCustomHeadView, initWithADContext_, context)
}

J2OBJC_CLASS_TYPE_LITERAL_SOURCE(ASDefaultCustomHeadView)

J2OBJC_NAME_MAPPING(ASDefaultCustomHeadView, "com.reginald.swiperefresh", "AS")
