//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: D:\Java\git\core-ios-widgets\IOSSwipeRefreshLayoutPlugin\src\main\java\com\ashera\swiperefreshlayout\DefaultCustomHeadViewImpl.java
//

#import <Foundation/Foundation.h>
#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_DefaultCustomHeadViewImpl")
#ifdef RESTRICT_DefaultCustomHeadViewImpl
#define INCLUDE_ALL_DefaultCustomHeadViewImpl 0
#else
#define INCLUDE_ALL_DefaultCustomHeadViewImpl 1
#endif
#undef RESTRICT_DefaultCustomHeadViewImpl

#if !defined (ASDefaultCustomHeadViewImpl_) && (INCLUDE_ALL_DefaultCustomHeadViewImpl || defined(INCLUDE_ASDefaultCustomHeadViewImpl))
#define ASDefaultCustomHeadViewImpl_

#define RESTRICT_BaseHasWidgets 1
#define INCLUDE_ASBaseHasWidgets 1
#include "BaseHasWidgets.h"

@class ASWidgetAttribute;
@class IOSClass;
@class JavaLangBoolean;
@class JavaLangInteger;
@class NSString;
@protocol ASIFragment;
@protocol ASILifeCycleDecorator;
@protocol ASIWidget;
@protocol JavaUtilMap;

@interface ASDefaultCustomHeadViewImpl : ASBaseHasWidgets
@property id uiView;

#pragma mark Public

- (instancetype)init;

- (instancetype)initWithNSString:(NSString *)localname;

- (instancetype)initWithNSString:(NSString *)groupName
                    withNSString:(NSString *)localname;

- (void)addWithASIWidget:(id<ASIWidget>)w
                 withInt:(int32_t)index;

- (id)asNativeWidget;

- (id)asWidget;

- (bool)checkIosVersionWithNSString:(NSString *)v;

- (void)createWithASIFragment:(id<ASIFragment>)fragment
              withJavaUtilMap:(id<JavaUtilMap>)params;

- (id)getAttributeWithASWidgetAttribute:(ASWidgetAttribute *)key
              withASILifeCycleDecorator:(id<ASILifeCycleDecorator>)decorator;

- (id)getChildAttributeWithASIWidget:(id<ASIWidget>)w
               withASWidgetAttribute:(ASWidgetAttribute *)key;

- (IOSClass *)getViewClass;

- (void)invalidate;

- (void)loadAttributesWithNSString:(NSString *)localName;

- (void)nativeCreateWithJavaUtilMap:(id<JavaUtilMap>)params;

- (id<ASIWidget>)newInstance OBJC_METHOD_FAMILY_NONE;

- (bool)removeWithInt:(int32_t)index;

- (bool)removeWithASIWidget:(id<ASIWidget>)w;

- (void)requestLayout;

- (void)setAttributeWithASWidgetAttribute:(ASWidgetAttribute *)key
                             withNSString:(NSString *)strValue
                                   withId:(id)objValue
                withASILifeCycleDecorator:(id<ASILifeCycleDecorator>)decorator;

- (void)setChildAttributeWithASIWidget:(id<ASIWidget>)w
                 withASWidgetAttribute:(ASWidgetAttribute *)key
                          withNSString:(NSString *)strValue
                                withId:(id)objValue;

- (void)setIdWithNSString:(NSString *)id_;

- (void)setVisibleWithBoolean:(bool)b;

@end

J2OBJC_EMPTY_STATIC_INIT(ASDefaultCustomHeadViewImpl)

inline NSString *ASDefaultCustomHeadViewImpl_get_LOCAL_NAME(void);
/*! INTERNAL ONLY - Use accessor function from above. */
FOUNDATION_EXPORT NSString *ASDefaultCustomHeadViewImpl_LOCAL_NAME;
J2OBJC_STATIC_FIELD_OBJ_FINAL(ASDefaultCustomHeadViewImpl, LOCAL_NAME, NSString *)

inline NSString *ASDefaultCustomHeadViewImpl_get_GROUP_NAME(void);
/*! INTERNAL ONLY - Use accessor function from above. */
FOUNDATION_EXPORT NSString *ASDefaultCustomHeadViewImpl_GROUP_NAME;
J2OBJC_STATIC_FIELD_OBJ_FINAL(ASDefaultCustomHeadViewImpl, GROUP_NAME, NSString *)

FOUNDATION_EXPORT void ASDefaultCustomHeadViewImpl_init(ASDefaultCustomHeadViewImpl *self);

FOUNDATION_EXPORT ASDefaultCustomHeadViewImpl *new_ASDefaultCustomHeadViewImpl_init(void) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT ASDefaultCustomHeadViewImpl *create_ASDefaultCustomHeadViewImpl_init(void);

FOUNDATION_EXPORT void ASDefaultCustomHeadViewImpl_initWithNSString_(ASDefaultCustomHeadViewImpl *self, NSString *localname);

FOUNDATION_EXPORT ASDefaultCustomHeadViewImpl *new_ASDefaultCustomHeadViewImpl_initWithNSString_(NSString *localname) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT ASDefaultCustomHeadViewImpl *create_ASDefaultCustomHeadViewImpl_initWithNSString_(NSString *localname);

FOUNDATION_EXPORT void ASDefaultCustomHeadViewImpl_initWithNSString_withNSString_(ASDefaultCustomHeadViewImpl *self, NSString *groupName, NSString *localname);

FOUNDATION_EXPORT ASDefaultCustomHeadViewImpl *new_ASDefaultCustomHeadViewImpl_initWithNSString_withNSString_(NSString *groupName, NSString *localname) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT ASDefaultCustomHeadViewImpl *create_ASDefaultCustomHeadViewImpl_initWithNSString_withNSString_(NSString *groupName, NSString *localname);

J2OBJC_TYPE_LITERAL_HEADER(ASDefaultCustomHeadViewImpl)

@compatibility_alias ComAsheraSwiperefreshlayoutDefaultCustomHeadViewImpl ASDefaultCustomHeadViewImpl;


#endif

#if !defined (ASDefaultCustomHeadViewImpl_Divider_) && (INCLUDE_ALL_DefaultCustomHeadViewImpl || defined(INCLUDE_ASDefaultCustomHeadViewImpl_Divider))
#define ASDefaultCustomHeadViewImpl_Divider_

#define RESTRICT_AbstractBitFlagConverter 1
#define INCLUDE_ASAbstractBitFlagConverter 1
#include "AbstractBitFlagConverter.h"

@class JavaLangInteger;
@protocol JavaUtilMap;

@interface ASDefaultCustomHeadViewImpl_Divider : ASAbstractBitFlagConverter

#pragma mark Public

- (JavaLangInteger *)getDefault;

- (id<JavaUtilMap>)getMapping;

#pragma mark Package-Private

- (instancetype)init;

@end

J2OBJC_EMPTY_STATIC_INIT(ASDefaultCustomHeadViewImpl_Divider)

FOUNDATION_EXPORT void ASDefaultCustomHeadViewImpl_Divider_init(ASDefaultCustomHeadViewImpl_Divider *self);

FOUNDATION_EXPORT ASDefaultCustomHeadViewImpl_Divider *new_ASDefaultCustomHeadViewImpl_Divider_init(void) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT ASDefaultCustomHeadViewImpl_Divider *create_ASDefaultCustomHeadViewImpl_Divider_init(void);

J2OBJC_TYPE_LITERAL_HEADER(ASDefaultCustomHeadViewImpl_Divider)


#endif

#if !defined (ASDefaultCustomHeadViewImpl_Orientation_) && (INCLUDE_ALL_DefaultCustomHeadViewImpl || defined(INCLUDE_ASDefaultCustomHeadViewImpl_Orientation))
#define ASDefaultCustomHeadViewImpl_Orientation_

#define RESTRICT_AbstractEnumToIntConverter 1
#define INCLUDE_ASAbstractEnumToIntConverter 1
#include "AbstractEnumToIntConverter.h"

@class JavaLangInteger;
@protocol JavaUtilMap;

@interface ASDefaultCustomHeadViewImpl_Orientation : ASAbstractEnumToIntConverter

#pragma mark Public

- (JavaLangInteger *)getDefault;

- (id<JavaUtilMap>)getMapping;

#pragma mark Package-Private

- (instancetype)init;

@end

J2OBJC_EMPTY_STATIC_INIT(ASDefaultCustomHeadViewImpl_Orientation)

FOUNDATION_EXPORT void ASDefaultCustomHeadViewImpl_Orientation_init(ASDefaultCustomHeadViewImpl_Orientation *self);

FOUNDATION_EXPORT ASDefaultCustomHeadViewImpl_Orientation *new_ASDefaultCustomHeadViewImpl_Orientation_init(void) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT ASDefaultCustomHeadViewImpl_Orientation *create_ASDefaultCustomHeadViewImpl_Orientation_init(void);

J2OBJC_TYPE_LITERAL_HEADER(ASDefaultCustomHeadViewImpl_Orientation)


#endif

#if !defined (ASDefaultCustomHeadViewImpl_DefaultCustomHeadViewExt_) && (INCLUDE_ALL_DefaultCustomHeadViewImpl || defined(INCLUDE_ASDefaultCustomHeadViewImpl_DefaultCustomHeadViewExt))
#define ASDefaultCustomHeadViewImpl_DefaultCustomHeadViewExt_

#define RESTRICT_DefaultCustomHeadView 1
#define INCLUDE_ASDefaultCustomHeadView 1
#include "DefaultCustomHeadView.h"

#define RESTRICT_ILifeCycleDecorator 1
#define INCLUDE_ASILifeCycleDecorator 1
#include "ILifeCycleDecorator.h"

#define RESTRICT_IMaxDimension 1
#define INCLUDE_ASIMaxDimension 1
#include "IMaxDimension.h"

@class ADContext;
@class ADRect;
@class ADView;
@class ASDefaultCustomHeadViewImpl;
@class ASWidgetAttribute;
@class IOSIntArray;
@class IOSObjectArray;
@class JavaLangBoolean;
@class JavaLangInteger;
@class NSString;
@protocol ASIWidget;
@protocol JavaUtilList;

@interface ASDefaultCustomHeadViewImpl_DefaultCustomHeadViewExt : ASDefaultCustomHeadView < ASILifeCycleDecorator, ASIMaxDimension >

#pragma mark Public

- (instancetype)initWithASDefaultCustomHeadViewImpl:(ASDefaultCustomHeadViewImpl *)outer$;

- (void)drawableStateChanged;

- (void)endViewTransitionWithADView:(ADView *)view;

- (void)executeWithNSString:(NSString *)method
          withNSObjectArray:(IOSObjectArray *)canvas;

- (id)getAttributeWithASWidgetAttribute:(ASWidgetAttribute *)widgetAttribute;

- (void)getLocationOnScreenWithIntArray:(IOSIntArray *)appScreenLocation;

- (int32_t)getMaxHeight;

- (int32_t)getMaxWidth;

- (id<JavaUtilList>)getMethods;

- (id<ASIWidget>)getWidget;

- (void)getWindowVisibleDisplayFrameWithADRect:(ADRect *)displayFrame;

- (ADView *)inflateViewWithNSString:(NSString *)layout;

- (void)initialized OBJC_METHOD_FAMILY_NONE;

- (id<ASILifeCycleDecorator>)newInstanceWithASIWidget:(id<ASIWidget>)widget OBJC_METHOD_FAMILY_NONE;

- (void)offsetLeftAndRightWithInt:(int32_t)offset;

- (void)offsetTopAndBottomWithInt:(int32_t)offset;

- (void)onMeasureWithInt:(int32_t)widthMeasureSpec
                 withInt:(int32_t)heightMeasureSpec;

- (void)remeasure;

- (void)removeFromParent;

- (void)setAttributeWithASWidgetAttribute:(ASWidgetAttribute *)widgetAttribute
                             withNSString:(NSString *)strValue
                                   withId:(id)objValue;

- (void)setMaxHeightWithInt:(int32_t)height;

- (void)setMaxWidthWithInt:(int32_t)width;

- (void)setMyAttributeWithNSString:(NSString *)name
                            withId:(id)value;

- (void)setState0WithId:(id)value;

- (void)setState1WithId:(id)value;

- (void)setState2WithId:(id)value;

- (void)setState3WithId:(id)value;

- (void)setState4WithId:(id)value;

- (void)setVisibilityWithInt:(int32_t)visibility;

- (void)state0;

- (void)state1;

- (void)state2;

- (void)state3;

- (void)state4;

- (void)stateNo;

- (void)stateYes;

- (void)updateMeasuredDimensionWithInt:(int32_t)width
                               withInt:(int32_t)height;

#pragma mark Protected

- (void)onLayoutWithBoolean:(bool)changed
                    withInt:(int32_t)l
                    withInt:(int32_t)t
                    withInt:(int32_t)r
                    withInt:(int32_t)b;

// Disallowed inherited constructors, do not use.

- (instancetype)init NS_UNAVAILABLE;

- (instancetype)initWithADContext:(ADContext *)arg0 NS_UNAVAILABLE;

@end

J2OBJC_EMPTY_STATIC_INIT(ASDefaultCustomHeadViewImpl_DefaultCustomHeadViewExt)

FOUNDATION_EXPORT void ASDefaultCustomHeadViewImpl_DefaultCustomHeadViewExt_initWithASDefaultCustomHeadViewImpl_(ASDefaultCustomHeadViewImpl_DefaultCustomHeadViewExt *self, ASDefaultCustomHeadViewImpl *outer$);

FOUNDATION_EXPORT ASDefaultCustomHeadViewImpl_DefaultCustomHeadViewExt *new_ASDefaultCustomHeadViewImpl_DefaultCustomHeadViewExt_initWithASDefaultCustomHeadViewImpl_(ASDefaultCustomHeadViewImpl *outer$) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT ASDefaultCustomHeadViewImpl_DefaultCustomHeadViewExt *create_ASDefaultCustomHeadViewImpl_DefaultCustomHeadViewExt_initWithASDefaultCustomHeadViewImpl_(ASDefaultCustomHeadViewImpl *outer$);

J2OBJC_TYPE_LITERAL_HEADER(ASDefaultCustomHeadViewImpl_DefaultCustomHeadViewExt)


#endif

#pragma pop_macro("INCLUDE_ALL_DefaultCustomHeadViewImpl")
