//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: D:\Java\git\core-ios-widgets\IOSSwipeRefreshLayoutPlugin\src\main\java\com\ashera\swiperefreshlayout\SwipeRefreshLayoutPlugin.java
//

#import <Foundation/Foundation.h>
#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_SwipeRefreshLayoutPlugin")
#ifdef RESTRICT_SwipeRefreshLayoutPlugin
#define INCLUDE_ALL_SwipeRefreshLayoutPlugin 0
#else
#define INCLUDE_ALL_SwipeRefreshLayoutPlugin 1
#endif
#undef RESTRICT_SwipeRefreshLayoutPlugin

#if !defined (ASSwipeRefreshLayoutPlugin_) && (INCLUDE_ALL_SwipeRefreshLayoutPlugin || defined(INCLUDE_ASSwipeRefreshLayoutPlugin))
#define ASSwipeRefreshLayoutPlugin_

@interface ASSwipeRefreshLayoutPlugin : NSObject

#pragma mark Public

- (instancetype)init;

+ (void)initPlugin OBJC_METHOD_FAMILY_NONE;

@end

J2OBJC_EMPTY_STATIC_INIT(ASSwipeRefreshLayoutPlugin)

FOUNDATION_EXPORT void ASSwipeRefreshLayoutPlugin_init(ASSwipeRefreshLayoutPlugin *self);

FOUNDATION_EXPORT ASSwipeRefreshLayoutPlugin *new_ASSwipeRefreshLayoutPlugin_init(void) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT ASSwipeRefreshLayoutPlugin *create_ASSwipeRefreshLayoutPlugin_init(void);

FOUNDATION_EXPORT void ASSwipeRefreshLayoutPlugin_initPlugin(void);

J2OBJC_TYPE_LITERAL_HEADER(ASSwipeRefreshLayoutPlugin)

@compatibility_alias ComAsheraSwiperefreshlayoutSwipeRefreshLayoutPlugin ASSwipeRefreshLayoutPlugin;


#endif

#pragma pop_macro("INCLUDE_ALL_SwipeRefreshLayoutPlugin")
