//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: D:\Java\git\core-ios-widgets\IOSSwipeRefreshLayoutPlugin\src\main\java\com\ashera\swiperefreshlayout\SwipeRefreshLayoutPlugin.java
//

#define J2OBJC_IMPORTED_BY_JAVA_IMPLEMENTATION 1




#include "CustomSwipeRefreshLayoutImpl.h"
#include "DefaultCustomHeadViewImpl.h"
#include "J2ObjC_source.h"
#include "SwipeRefreshLayoutPlugin.h"
#include "WidgetFactory.h"




#pragma clang diagnostic error "-Wreturn-type"
#pragma clang diagnostic ignored "-Wswitch"


@implementation ASSwipeRefreshLayoutPlugin

J2OBJC_IGNORE_DESIGNATED_BEGIN
- (instancetype)init {
  ASSwipeRefreshLayoutPlugin_init(self);
  return self;
}
J2OBJC_IGNORE_DESIGNATED_END

+ (void)initPlugin {
  ASSwipeRefreshLayoutPlugin_initPlugin();
}

+ (const J2ObjcClassInfo *)__metadata {
  static J2ObjcMethodInfo methods[] = {
    { NULL, NULL, 0x1, -1, -1, -1, -1, -1, -1 },
    { NULL, "V", 0x9, -1, -1, -1, -1, -1, -1 },
  };
  #pragma clang diagnostic push
  #pragma clang diagnostic ignored "-Wobjc-multiple-method-names"
  #pragma clang diagnostic ignored "-Wundeclared-selector"
  methods[0].selector = @selector(init);
  methods[1].selector = @selector(initPlugin);
  #pragma clang diagnostic pop
  static const J2ObjcClassInfo _ASSwipeRefreshLayoutPlugin = { "SwipeRefreshLayoutPlugin", "com.ashera.swiperefreshlayout", NULL, methods, NULL, 7, 0x1, 2, 0, -1, -1, -1, -1, -1 };
  return &_ASSwipeRefreshLayoutPlugin;
}

@end

void ASSwipeRefreshLayoutPlugin_init(ASSwipeRefreshLayoutPlugin *self) {
  NSObject_init(self);
}

ASSwipeRefreshLayoutPlugin *new_ASSwipeRefreshLayoutPlugin_init() {
  J2OBJC_NEW_IMPL(ASSwipeRefreshLayoutPlugin, init)
}

ASSwipeRefreshLayoutPlugin *create_ASSwipeRefreshLayoutPlugin_init() {
  J2OBJC_CREATE_IMPL(ASSwipeRefreshLayoutPlugin, init)
}

void ASSwipeRefreshLayoutPlugin_initPlugin() {
  ASSwipeRefreshLayoutPlugin_initialize();
  ASWidgetFactory_register__WithASIWidget_(new_ASCustomSwipeRefreshLayoutImpl_init());
  ASWidgetFactory_register__WithASIWidget_(new_ASDefaultCustomHeadViewImpl_init());
}

J2OBJC_CLASS_TYPE_LITERAL_SOURCE(ASSwipeRefreshLayoutPlugin)

J2OBJC_NAME_MAPPING(ASSwipeRefreshLayoutPlugin, "com.ashera.swiperefreshlayout", "AS")
